{{- if .Values.persistence.enabled -}}
{{- $persistentBlocks := dict
  "config" .Values.persistence.config
  "data" .Values.persistence.data
  "backups" .Values.persistence.backups
-}}
{{- range $name, $p := $persistentBlocks }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "phlex.fullname" $ }}-{{ $name }}
  labels:
    {{- include "phlex.labels" $ | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $p.size }}
  {{- if $p.storageClass }}
  storageClassName: {{ $p.storageClass }}
  {{- end }}
{{- end }}
{{- if .Values.persistence.logs.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "phlex.fullname" . }}-logs
  labels:
    {{- include "phlex.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.logs.size }}
  {{- if .Values.persistence.logs.storageClass }}
  storageClassName: {{ .Values.persistence.logs.storageClass }}
  {{- end }}
{{- end }}
{{- if .Values.persistence.recordings.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "phlex.fullname" . }}-recordings
  labels:
    {{- include "phlex.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.recordings.size }}
  {{- if .Values.persistence.recordings.storageClass }}
  storageClassName: {{ .Values.persistence.recordings.storageClass }}
  {{- end }}
{{- end }}
{{- if .Values.persistence.media.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "phlex.fullname" . }}-media
  labels:
    {{- include "phlex.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.persistence.media.size }}
  {{- if .Values.persistence.media.storageClass }}
  storageClassName: {{ .Values.persistence.media.storageClass }}
  {{- end }}
{{- end }}
{{- end -}}
