{{- if .Values.persistence.enabled }}
{{- range $name, $persistence := dict "config" .Values.persistence.config "data" .Values.persistence.data "backups" .Values.persistence.backups }}
{{- if $persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "phlex.fullname" $ }}-{{ $name }}
  labels:
    {{- include "phlex.labels" $ | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $persistence.size }}
  {{- if $persistence.storageClass }}
  storageClassName: {{ $persistence.storageClass }}
  {{- end }}
{{- end }}
{{- end }}
---
{{- if .Values.persistence.media.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "phlex.fullname" . }}-media
  labels:
    {{- include "phlex.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.persistence.media.size }}
  {{- if .Values.persistence.media.storageClass }}
  storageClassName: {{ .Values.persistence.media.storageClass }}
  {{- end }}
{{- end }}
{{- end }}
