-- Migration: 027_library_scan_jobs.sql
-- Description: Library scan-job store (Step 1.1a).
--
-- Records the lifecycle of a library scan (queued -> running ->
-- completed/failed) together with its progress counters. This table is the
-- foundation that the 1.1b async scan worker writes to (claim a queued job,
-- update progress, mark completed/failed) and that the scan-status /
-- scan-history endpoints read from. The transport is this DB table itself —
-- there is no Redis / queue library in the stack (decided 2026-05-27).
--
-- `id` is a CHAR(36) UUID generated by the local generateUuid() helper, in
-- keeping with every other table. `library_id` carries a FK to libraries.id
-- with ON DELETE CASCADE so a removed library cleans up its scan history.
-- `type` distinguishes an incremental `scan` from a purge-and-rescan
-- `rescan`; `status` tracks the job lifecycle. The `items_*` columns are
-- progress counters and `current_path` is a human-readable progress hint.
--
-- Idempotent: `CREATE TABLE IF NOT EXISTS` means the migration runner can
-- replay this file safely (the runner also downgrades duplicate-object errors
-- to notes — see scripts/run-migrations.php).

CREATE TABLE IF NOT EXISTS `library_scan_jobs` (
    `id` CHAR(36) NOT NULL PRIMARY KEY COMMENT 'UUID identifier',
    `library_id` CHAR(36) NOT NULL COMMENT 'FK -> libraries.id',
    `type` ENUM('scan', 'rescan') NOT NULL DEFAULT 'scan'
        COMMENT 'scan=incremental, rescan=purge+rescan',
    `status` ENUM('queued', 'running', 'completed', 'failed') NOT NULL DEFAULT 'queued'
        COMMENT 'job lifecycle state',
    `items_found` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'items discovered so far',
    `items_added` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'new items inserted',
    `items_updated` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'existing items updated',
    `items_removed` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'items removed (rescan)',
    `current_path` VARCHAR(1024) NULL COMMENT 'path currently being scanned (progress hint)',
    `error` TEXT NULL COMMENT 'failure message when status=failed',
    `queued_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'when enqueued',
    `started_at` TIMESTAMP NULL COMMENT 'when the worker claimed it',
    `completed_at` TIMESTAMP NULL COMMENT 'when it finished (completed or failed)',
    INDEX `idx_lsj_library` (`library_id`),
    INDEX `idx_lsj_status` (`status`),
    INDEX `idx_lsj_library_queued` (`library_id`, `queued_at`),
    CONSTRAINT `fk_lsj_library` FOREIGN KEY (`library_id`)
        REFERENCES `libraries` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
