[supervisord]
nodaemon=true
user=root
logfile=/var/phlex/logs/supervisord.log
pidfile=/var/run/supervisord.pid
loglevel=info

[program:php-fpm]
command=php-fpm -F
autostart=true
autorestart=true
stdout_logfile=/var/phlex/logs/php-fpm.log
stderr_logfile=/var/phlex/logs/php-fpm-error.log
user=nobody

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/phlex/logs/nginx.log
stderr_logfile=/var/phlex/logs/nginx-error.log

[program:workerman]
command=php /var/www/html/public/index.php start
autostart=true
autorestart=true
stdout_logfile=/var/phlex/logs/workerman.log
stderr_logfile=/var/phlex/logs/workerman-error.log
user=nobody
numprocs=1
