tcp:
  routers:
    phlix-relay:
      rule: "HostSNI(`*`)"
      service: phlix-relay-service
      passthrough: true

  services:
    phlix-relay-service:
      loadBalancer:
        servers:
          - address: "phlix-hub:3473"
