apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "phlix-hub.fullname" . }}
  labels:
    {{- include "phlix-hub.labels" . | nindent 4 }}
data:
  PHLIX_HUB_APP_ENV: "production"
  PHLIX_HUB_LOG_LEVEL: {{ .Values.config.log_level | quote }}
  {{- if .Values.config.public_url }}
  PHLIX_HUB_PUBLIC_URL: {{ .Values.config.public_url | quote }}
  {{- end }}
