apiVersion: v1
kind: Service
metadata:
  name: {{ include "phlix-hub.fullname" . }}
  labels:
    {{- include "phlix-hub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.relay.port }}
      targetPort: relay
      protocol: TCP
      name: relay
  selector:
    {{- include "phlix-hub.selectorLabels" . | nindent 4 }}
