<?php

declare(strict_types=1);

namespace Phlix\Tests\Unit\Support;

use DOMDocument;
use PHPUnit\Framework\TestCase;

/**
 * S345 — a skip set must be comparable BY NAME, not by count.
 *
 * ## What was actually wrong, measured rather than asserted
 *
 * `phpunit.xml` displayed details for deprecations, warnings and errors, and NOT for
 * skipped tests, and no workflow passed the CLI flag either. So the only thing any run
 * of this suite published about its skips was the number in
 * `Tests: N, ..., Skipped: M.`. Measured on master run `32027697809`
 * (head `e5099b88`): the log says `Skipped: 3` and contains ZERO
 * `There were N skipped tests:` sections.
 *
 * A count cannot distinguish the three things that move it —
 *
 *   1. a test STARTED skipping (a real regression),
 *   2. a conditionally-skipped test turned into a FAILURE (it left the skip set),
 *   3. a test DISAPPEARED (deleted, renamed, or no longer collected),
 *
 * — and it drifts on its own between runs, because this repo has legitimate
 * environment-dependent skips: CI reports 3 where a box with no MySQL, no Chromium and
 * no mysqldump reports ~259. Worse, 1 and 2 can happen together and leave the count
 * UNMOVED. Two audits were forced to record skip movement as "unproven" for exactly
 * this reason. A NAME SET compared with `comm` separates all three.
 *
 * ## Why half of this file drives the REAL phpunit binary
 *
 * The first cut of this test pinned the script against a hand-written constant that
 * mirrored PHPUnit's output. That fixture was, by construction, unable to notice that
 * the real thing differs — and it differed twice:
 *
 *   * `--testdox` can NEVER name a skipped test. PHPUnit builds the default result
 *     printer for a testdox run with `$displayDetailsOnSkippedTests` hardcoded `false`
 *     (`vendor/phpunit/phpunit/src/TextUI/Output/Facade.php:204-221`), so the config
 *     value is not consulted at all. `syncplay-e2e.yml:90` passed `--testdox`; the
 *     fixture could not see it, and the script blamed `phpunit.xml` for it.
 *   * a skipped test SUITE is counted in the same `Skipped: N` (`SummaryPrinter.php:106`)
 *     but named under a DIFFERENT header, with no `::` in its entries — and a run in
 *     which every suite skipped prints `No tests executed!` and no `Tests:` line at all.
 *
 * So the shapes are now RE-DERIVED from `./vendor/bin/phpunit` in a subprocess
 * (`tests/Unit/Admin/BackupManagerTest.php` skips exactly one test unconditionally and
 * runs in ~0.03 s; the suite-skip shape is generated by writing a throwaway test class
 * with a skipping `setUpBeforeClass()`). Hand-written fixtures are kept ONLY for the
 * shapes the binary cannot produce here: a `gh run view --log` prefix, a whole-workflow
 * log containing several runs, and format DRIFT.
 *
 * ## What this test pins, and what it deliberately does not
 *
 * Two halves, and both must hold or the guarantee is gone:
 *
 *   * `phpunit.xml` carries `displayDetailsOnSkippedTests="true"` — checked against the
 *     PARSED document, not the file's text, so commenting the root element's attribute
 *     out cannot pass. Deleting it is otherwise SILENT: every run stays green and every
 *     count keeps being reported, and the loss shows up only the next time somebody
 *     needs a name set and no longer has one.
 *   * `scripts/skipped-test-names.sh` still turns that output into a sorted,
 *     `comm`-ready set — and every refusal path names a cause that is TRUE for the input
 *     that triggered it, because a parser that quietly matches NOTHING reads as a pass
 *     and a WRONG diagnosis is worse than none.
 *
 * It does NOT try to defend the script against being rewritten, and it does not assert
 * a skip COUNT anywhere. Asserting a count here would reintroduce the exact measure the
 * step exists to replace.
 */
final class SkippedTestNameReportingTest extends TestCase
{
    private const REPO = __DIR__ . '/../../..';

    private const SCRIPT = self::REPO . '/scripts/skipped-test-names.sh';

    private const CONFIG = self::REPO . '/phpunit.xml';

    /**
     * A test file with exactly ONE skip, taken unconditionally in the method body
     * (`BackupManagerTest.php:30`), so the real-binary expectations below do not depend
     * on MySQL, Chromium, FFI or anything else about the box.
     */
    private const REAL_TEST_FILE = 'tests/Unit/Admin/BackupManagerTest.php';

    private const REAL_SKIPPED_NAME = 'Phlix\Tests\Unit\Admin\BackupManagerTest::testCreateBackupGeneratesIdAndPath';

    /**
     * A minimal but realistic PHPUnit 10.5 tail: a first list (so the `--` separator is
     * present, as it is in a real red run), the skipped-details list, and the summary.
     * Kept for the shapes the real binary cannot produce here — the `gh` log prefix and
     * deliberate format drift.
     */
    private const FIXTURE = <<<'OUT'
        PHPUnit 10.5.64 by Sebastian Bergmann and contributors.

        Runtime:       PHP 8.3.6
        Configuration: /repo/phpunit.xml

        There was 1 failure:

        1) Phlix\Tests\Unit\Zeta\ZetaTest::testUnrelated
        Failed asserting that false is true.

        --

        There were 4 skipped tests:

        1) Phlix\Tests\Integration\Media\MusicDtoTest::testColumnIsChar36
        No MySQL on 127.0.0.1:3306

        /repo/tests/Support/Database/RequiresRealDatabase.php:41

        2) Phlix\Tests\E2E\Media\Transcoding\Fmp4HlsPlaybackE2ETest::testRemovingTheExtXMapBreaksPlayback
        no Chrome/Chromium binary

        3) Phlix\Tests\Unit\Admin\BackupManagerTest::testCreateBackupGeneratesIdAndPath with data set "a b"
        createBackup requires mysqldump

        4) Phlix\Tests\Unit\Alpha\AlphaTest::testGamma
        FFI is not available on this system

        FAILURES!
        Tests: 9, Assertions: 12, Failures: 1, Skipped: 4.
        OUT;

    /** @var list<string> */
    private const EXPECTED_NAMES = [
        'Phlix\Tests\E2E\Media\Transcoding\Fmp4HlsPlaybackE2ETest::testRemovingTheExtXMapBreaksPlayback',
        'Phlix\Tests\Integration\Media\MusicDtoTest::testColumnIsChar36',
        'Phlix\Tests\Unit\Admin\BackupManagerTest::testCreateBackupGeneratesIdAndPath with data set "a b"',
        'Phlix\Tests\Unit\Alpha\AlphaTest::testGamma',
    ];

    /**
     * Two names whose byte order (`LC_ALL=C`) is the REVERSE of their order under a
     * UTF-8 collation, because `\` (0x5C) sorts after `B` (0x42) byte-wise while a
     * locale-aware sort ignores the punctuation at the first level. GNU `comm` compares
     * byte-wise, so the C order is the only one it accepts.
     */
    private const C_ORDER_PAIR = [
        'Phlix\Tests\UnitB\ATest::testA',
        'Phlix\Tests\Unit\Admin\ZTest::testA',
    ];

    private string $tmpDir = '';

    protected function setUp(): void
    {
        $dir = sys_get_temp_dir() . '/phlix-s345-' . bin2hex(random_bytes(6));
        self::assertTrue(mkdir($dir, 0o700), 'could not create the fixture directory');
        $this->tmpDir = $dir;
    }

    protected function tearDown(): void
    {
        if ($this->tmpDir === '') {
            return;
        }

        foreach ((glob($this->tmpDir . '/*') ?: []) as $file) {
            @unlink($file);
        }

        @rmdir($this->tmpDir);
        $this->tmpDir = '';
    }

    public function test_phpunit_xml_still_asks_for_skipped_test_names(): void
    {
        $document = new DOMDocument();
        self::assertTrue(
            $document->load(self::CONFIG),
            'phpunit.xml could not be parsed.',
        );

        $root = $document->documentElement;
        self::assertNotNull($root, 'phpunit.xml has no root element.');

        self::assertSame(
            'true',
            $root->getAttribute('displayDetailsOnSkippedTests'),
            'phpunit.xml has lost displayDetailsOnSkippedTests="true" (S345). Without it PHPUnit '
            . 'prints only the skip COUNT, and a count cannot distinguish a test that started '
            . 'skipping from one that turned into a failure from one that disappeared. Removing it '
            . 'is otherwise SILENT — every run stays green. Restore the attribute; do not delete '
            . 'this test.',
        );
    }

    public function test_the_extraction_script_is_present_and_executable(): void
    {
        self::assertFileExists(
            self::SCRIPT,
            'scripts/skipped-test-names.sh is gone. It is the documented way to turn a run into a '
            . '`comm`-ready name set (README, "Comparing skip sets between two runs").',
        );
        self::assertTrue(
            is_executable(self::SCRIPT),
            'scripts/skipped-test-names.sh has lost its executable bit, so the documented '
            . '`| scripts/skipped-test-names.sh` pipeline no longer runs.',
        );
    }

    public function test_the_readme_documents_the_comm_ready_one_liner(): void
    {
        $readme = (string) file_get_contents(self::REPO . '/README.md');

        self::assertStringContainsString(
            'scripts/skipped-test-names.sh',
            $readme,
            'README.md no longer points at the extraction script. A one-liner that lives only in a '
            . 'PR description is not documentation.',
        );
        self::assertStringContainsString(
            'comm -3',
            $readme,
            'README.md no longer shows the `comm` comparison, which is the whole point of producing '
            . 'a name set rather than a count.',
        );
    }

    /**
     * No workflow may pass `--testdox` to PHPUnit, because such a run adds to
     * `Skipped: N` and can never name those skips (Facade.php:204-221) — so a
     * whole-workflow log stops being comparable. `syncplay-e2e.yml:90` used to.
     */
    public function test_no_workflow_invokes_phpunit_with_testdox(): void
    {
        $files = glob(self::REPO . '/.github/workflows/*.yml') ?: [];
        self::assertNotSame([], $files, 'no workflow files found — this guard would prove nothing');

        $offenders = [];

        foreach ($files as $file) {
            foreach (explode("\n", (string) file_get_contents($file)) as $number => $line) {
                $code = trim(preg_replace('/#.*$/', '', $line) ?? '');

                if (str_contains($code, 'phpunit') && str_contains($code, '--testdox')) {
                    $offenders[] = basename($file) . ':' . ($number + 1) . ' ' . $code;
                }
            }
        }

        self::assertSame(
            [],
            $offenders,
            "A workflow passes --testdox to PHPUnit (S345). PHPUnit constructs the default result\n"
            . "printer with \$displayDetailsOnSkippedTests hardcoded FALSE for testdox runs\n"
            . "(vendor/phpunit/phpunit/src/TextUI/Output/Facade.php:204-221), so that step counts its\n"
            . "skips in `Skipped: N` and can NEVER name them — neither phpunit.xml's\n"
            . "displayDetailsOnSkippedTests=\"true\" nor --display-skipped can fix it. It also makes a\n"
            . "whole-run `gh run view --log` un-comparable, because the count and the name set no\n"
            . "longer agree. Drop the flag:\n" . implode("\n", $offenders),
        );
    }

    // ---------------------------------------------------------------------------------
    // Shapes RE-DERIVED from the real phpunit binary
    // ---------------------------------------------------------------------------------

    public function test_a_real_run_yields_the_skipped_name_through_the_script(): void
    {
        $output = $this->runRealPhpunit([self::REAL_TEST_FILE]);

        self::assertStringContainsString(
            'skipped test:',
            $output,
            'the real binary printed no skipped-details list, so phpunit.xml is not reaching it',
        );

        $result = $this->runScript($this->fixtureFile('real.log', $output));

        self::assertSame(0, $result['exit'], $result['stderr'] . "\n--- phpunit output ---\n" . $output);
        self::assertSame([self::REAL_SKIPPED_NAME], $result['lines'], $result['stderr']);
    }

    public function test_a_real_testdox_run_is_reported_as_testdox_and_never_blamed_on_phpunit_xml(): void
    {
        $output = $this->runRealPhpunit([self::REAL_TEST_FILE, '--testdox']);

        // The premise, re-derived rather than assumed: testdox counts the skip and never names it.
        self::assertStringContainsString('Skipped: 1', $output, 'the testdox run did not skip anything');
        self::assertStringNotContainsString(
            'skipped test:',
            $output,
            'testdox now prints a skipped-details list — Facade.php changed, so the exit-5 '
            . 'diagnosis needs re-deriving',
        );

        $result = $this->runScript($this->fixtureFile('testdox.log', $output));

        self::assertSame(
            5,
            $result['exit'],
            "a --testdox run must be reported AS a testdox run (exit 5). Exit 4 here would be a\n"
            . "FALSE diagnosis — it blames phpunit.xml, which is correct, and sends the reader to\n"
            . "change a config that cannot affect this. stderr was:\n" . $result['stderr'],
        );
        self::assertSame([], $result['lines'], 'a partial set must not be written');
        self::assertStringContainsString('--testdox', $result['stderr']);
        self::assertStringContainsString('Facade.php:204-221', $result['stderr']);
        self::assertStringNotContainsString(
            'has lost displayDetailsOnSkippedTests',
            $result['stderr'],
            'the testdox case must NOT be diagnosed as a missing attribute — the attribute is '
            . 'present and PHPUnit ignores it on that path',
        );
    }

    public function test_a_real_skipped_test_suite_is_named_rather_than_counted(): void
    {
        $probe = $this->writeSuiteSkipProbe();

        // Suite skip ALONE: PHPUnit prints `No tests executed!` and NO `Tests:` line, so the
        // `Skipped: N` cross-check does not exist for this shape.
        $alone = $this->runRealPhpunit([$probe]);
        self::assertStringContainsString('skipped test suite:', $alone, 'no suite-skip list in the real output');
        self::assertStringContainsString('No tests executed!', $alone);
        self::assertStringNotContainsString('Tests: ', $alone, 'this shape is supposed to publish no totals line');

        $result = $this->runScript($this->fixtureFile('suite-alone.log', $alone));
        self::assertSame(0, $result['exit'], $result['stderr'] . "\n--- phpunit output ---\n" . $alone);
        self::assertSame(['SUITE:Phlix\Tests\Scratch\S345SuiteSkipProbeTest'], $result['lines'], $result['stderr']);

        // Suite skip PLUS a test skip: one `Skipped: 2`, two different headers.
        $mixed = $this->runRealPhpunit([$probe, self::REAL_TEST_FILE]);
        self::assertStringContainsString('Skipped: 2', $mixed, 'a suite skip must count towards Skipped: N');

        $result = $this->runScript($this->fixtureFile('suite-mixed.log', $mixed));
        self::assertSame(
            0,
            $result['exit'],
            "a skipped SUITE is part of `Skipped: N` but is named under its own header, so blaming\n"
            . "the config (exit 4) or the parser (exit 3) for it is a FALSE diagnosis. stderr:\n"
            . $result['stderr'] . "\n--- phpunit output ---\n" . $mixed,
        );
        self::assertSame(
            [
                self::REAL_SKIPPED_NAME,
                'SUITE:Phlix\Tests\Scratch\S345SuiteSkipProbeTest',
            ],
            $result['lines'],
            $result['stderr'],
        );
    }

    public function test_a_real_colorized_run_is_parsed_rather_than_refused(): void
    {
        // `colors="true"` in phpunit.xml means COLOR_AUTO, so a pipe is never colorized in
        // practice — but a human running `--colors=always` and pasting the log must not be told
        // "this is not a PHPUnit run". The summary lines are the ANSI-wrapped ones, which is
        // exactly what defeats the positive control if escapes are not stripped.
        $output = $this->runRealPhpunit([self::REAL_TEST_FILE, '--colors=always']);

        self::assertStringContainsString(
            "\033[",
            $output,
            'the run produced no ANSI escapes, so this test would not be measuring anything',
        );

        $result = $this->runScript($this->fixtureFile('colors.log', $output));

        self::assertSame(
            0,
            $result['exit'],
            'a colorized run parses correctly apart from the escapes, so refusing it as "not a '
            . "PHPUnit run\" would be a false diagnosis. stderr:\n" . $result['stderr'],
        );
        self::assertSame([self::REAL_SKIPPED_NAME], $result['lines'], $result['stderr']);
    }

    public function test_a_truncated_write_is_refused_instead_of_handing_comm_a_short_set(): void
    {
        // `sort`'s exit status must be checked: a failing write (ENOSPC here, SIGPIPE in a
        // pipeline) otherwise yields a TRUNCATED set and exit 0 — the precise "quietly wrong
        // set handed to comm" outcome the whole exit contract exists to prevent.
        $output = $this->runRealPhpunit([self::REAL_TEST_FILE]);
        $input = $this->fixtureFile('write-fail.log', $output);

        if (!is_writable('/dev/full')) {
            // No always-full device on this box, so the failure cannot be provoked; pin the
            // mechanism textually rather than reporting a pass that measured nothing.
            self::assertStringContainsString(
                'write_status',
                (string) file_get_contents(self::SCRIPT),
                '/dev/full is unavailable, so the truncated-write path cannot be exercised here; '
                . "the script must still check the status of its `sort` pipeline",
            );

            return;
        }

        $stderrFile = $this->tmpDir . '/full-stderr.txt';
        $exit = 0;
        exec(
            escapeshellarg(self::SCRIPT) . ' ' . escapeshellarg($input)
            . ' > /dev/full 2> ' . escapeshellarg($stderrFile),
            $ignored,
            $exit,
        );

        self::assertSame(6, $exit, (string) file_get_contents($stderrFile));
        self::assertStringContainsString(
            'stdout is TRUNCATED',
            (string) file_get_contents($stderrFile),
        );
    }

    // ---------------------------------------------------------------------------------
    // Hand-written shapes the binary cannot produce here
    // ---------------------------------------------------------------------------------

    public function test_it_emits_the_sorted_name_set_and_nothing_else(): void
    {
        $result = $this->runScript($this->fixtureFile('run.log'));

        self::assertSame(0, $result['exit'], $result['stderr']);
        self::assertSame(self::EXPECTED_NAMES, $result['lines'], $result['stderr']);

        // "nothing else", asserted on the RAW bytes rather than on a filtered array: a blank
        // line is a set member as far as `comm` is concerned, and leading whitespace changes
        // the byte comparison.
        self::assertSame(
            implode("\n", self::EXPECTED_NAMES) . "\n",
            $result['stdout'],
            'stdout must be exactly the set, newline-terminated, with no blank or indented lines',
        );

        // Sortedness is delivered by the assertion ABOVE, because the fixture lists the names
        // in a different order from the sorted one. Pin that premise instead of re-sorting an
        // already-sorted array, which cannot fail.
        $asPrinted = [];
        preg_match_all('/^[0-9]+\) (\S+::\S.*)$/m', self::FIXTURE, $matches);
        foreach ($matches[1] as $name) {
            $asPrinted[] = trim($name);
        }

        self::assertNotSame(
            self::EXPECTED_NAMES,
            array_slice($asPrinted, 1),
            'the fixture must print the names in an UNSORTED order, or the assertion above cannot '
            . 'prove that the script sorts',
        );
    }

    public function test_a_class_name_containing_digits_is_not_dropped(): void
    {
        // The bug the denominator caught: `Fmp4Hls…` and `OAuth2…` were silently lost.
        self::assertContains(
            'Phlix\Tests\E2E\Media\Transcoding\Fmp4HlsPlaybackE2ETest::testRemovingTheExtXMapBreaksPlayback',
            $this->runScript($this->fixtureFile('run.log'))['lines'],
        );
    }

    public function test_it_reads_a_gh_run_view_log_with_its_job_step_timestamp_prefix(): void
    {
        $prefixed = [];
        foreach (explode("\n", self::FIXTURE) as $line) {
            $prefixed[] = "PHPUnit Test Suite\tRun PHPUnit tests\t2026-08-20T06:22:33.1234567Z " . $line;
        }

        $result = $this->runScript($this->fixtureFile('gh.log', implode("\n", $prefixed)));

        self::assertSame(0, $result['exit'], $result['stderr']);
        self::assertSame(self::EXPECTED_NAMES, $result['lines'], $result['stderr']);
    }

    public function test_the_same_name_from_two_jobs_is_emitted_once(): void
    {
        // A whole-workflow log: tests/Unit/Server/ skips appear in both `test` and
        // `test-server`. Without `sort -u` the set has a duplicate line and `comm` reports a
        // difference that does not exist.
        $run = "PHPUnit 10.5.64\n\nThere was 1 skipped test:\n\n"
            . '1) ' . self::REAL_SKIPPED_NAME . "\nreason\n\n"
            . "OK, but some tests were skipped!\nTests: 4, Assertions: 4, Skipped: 1.\n";

        $result = $this->runScript($this->fixtureFile('two-jobs.log', $run . "\n" . $run));

        self::assertSame(0, $result['exit'], $result['stderr']);
        self::assertSame([self::REAL_SKIPPED_NAME], $result['lines'], $result['stderr']);
    }

    public function test_the_set_is_ordered_BYTE_wise_so_comm_accepts_it(): void
    {
        $run = "PHPUnit 10.5.64\n\nThere were 2 skipped tests:\n\n"
            . '1) ' . self::C_ORDER_PAIR[1] . "\nreason\n\n"
            . '2) ' . self::C_ORDER_PAIR[0] . "\nreason\n\n"
            . "OK, but some tests were skipped!\nTests: 4, Assertions: 4, Skipped: 2.\n";

        $file = $this->fixtureFile('locale.log', $run);
        $utf8Locale = $this->localeWhoseCollationDiffersFromC();

        // Run the script under a locale whose collation would reorder these two names, so that
        // dropping the script's own `LC_ALL=C` changes the output. `comm` compares byte-wise
        // (GNU coreutils 9.4: it rejects a locale-ordered file with "is not in sorted order").
        $result = $this->runScript($file, $utf8Locale === null ? [] : ['LC_ALL' => $utf8Locale]);

        self::assertSame(0, $result['exit'], $result['stderr']);
        self::assertSame(
            self::C_ORDER_PAIR,
            $result['lines'],
            'the set must be in BYTE order (LC_ALL=C), whatever locale the caller runs under, '
            . 'or GNU `comm` refuses it as unsorted. Ambient locale for this run: '
            . ($utf8Locale ?? 'none available that collates differently from C'),
        );

        if ($utf8Locale === null) {
            // No locale on this box reorders the pair, so the behavioural check above cannot
            // fail. Fall back to pinning the mechanism textually rather than reporting a pass
            // that proves nothing.
            self::assertStringContainsString(
                'LC_ALL=C sort -u',
                (string) file_get_contents(self::SCRIPT),
                'no locale on this box collates differently from C, so the byte-order property '
                . 'cannot be measured here; the script must still pin LC_ALL=C explicitly',
            );
        }
    }

    public function test_input_that_is_not_a_phpunit_run_is_refused_rather_than_reported_as_empty(): void
    {
        $result = $this->runScript($this->fixtureFile('junk.log', "hello\nworld\n"));

        self::assertSame(2, $result['exit'], 'a parser fed the wrong input must not read as "no skips"');
        self::assertSame([], $result['lines']);
        self::assertStringContainsString('no PHPUnit result summary', $result['stderr']);
    }

    public function test_a_run_that_skipped_tests_but_printed_no_names_is_refused(): void
    {
        // Exactly master's shape before S345: a count, and no detail list to read it from.
        $countOnly = "PHPUnit 10.5.64\n\nOK, but there were issues!\nTests: 9, Assertions: 12, Skipped: 4.\n";

        $result = $this->runScript($this->fixtureFile('countonly.log', $countOnly));

        self::assertSame(4, $result['exit'], 'a missing displayDetailsOnSkippedTests must be loud, not empty');
        self::assertSame([], $result['lines']);
        self::assertStringContainsString('displayDetailsOnSkippedTests', $result['stderr']);
    }

    public function test_a_run_with_no_skips_at_all_is_an_empty_set_and_a_success(): void
    {
        $clean = "PHPUnit 10.5.64\n\nOK (9 tests, 12 assertions)\n";

        $result = $this->runScript($this->fixtureFile('clean.log', $clean));

        self::assertSame(0, $result['exit'], $result['stderr']);
        self::assertSame([], $result['lines']);
    }

    public function test_extraction_that_disagrees_with_phpunits_own_count_is_refused(): void
    {
        // One name mangled: PHPUnit still declares 4, only 3 are recoverable.
        $drifted = str_replace(
            '4) Phlix\Tests\Unit\Alpha\AlphaTest::testGamma',
            '4) something the parser cannot read',
            self::FIXTURE,
        );

        $result = $this->runScript($this->fixtureFile('drift.log', $drifted));

        self::assertSame(3, $result['exit'], 'a partial extraction must not be handed to `comm` as if complete');
        self::assertSame([], $result['lines']);
        self::assertStringContainsString('entry format has drifted', $result['stderr']);
    }

    /**
     * The branch findings 1 and 2 both fired and which nothing reached: the summaries
     * report MORE skips than the detail lists declared, without testdox output to explain
     * it and with a non-empty list (so neither exit 5 nor exit 4 applies). The shape is
     * real — a whole-workflow log in which one job did not load `phpunit.xml`.
     */
    public function test_a_list_that_names_fewer_skips_than_the_summary_is_refused_as_partial(): void
    {
        $partial = "PHPUnit 10.5.64\n\nThere was 1 skipped test:\n\n"
            . "1) Phlix\Tests\Unit\Alpha\AlphaTest::testGamma\nreason\n\n"
            . "OK, but some tests were skipped!\nTests: 9, Assertions: 12, Skipped: 3.\n";

        $result = $this->runScript($this->fixtureFile('partial.log', $partial));

        self::assertSame(3, $result['exit'], 'a set missing 2 of 3 names must not be handed to `comm`');
        self::assertSame([], $result['lines'], 'a PARTIAL set must not be written');
        self::assertStringContainsString('2 name(s) are missing', $result['stderr']);
    }

    /**
     * The mirror image, and the reason the `No tests executed!` allowance is conditional:
     * MORE declared than summarised, with no run reporting `No tests executed!`, can only
     * be the parser over-counting.
     */
    public function test_a_list_that_names_more_skips_than_the_summary_is_refused_as_drift(): void
    {
        $over = "PHPUnit 10.5.64\n\nThere were 2 skipped tests:\n\n"
            . "1) Phlix\Tests\Unit\Alpha\AlphaTest::testGamma\nreason\n\n"
            . "2) Phlix\Tests\Unit\Beta\BetaTest::testDelta\nreason\n\n"
            . "OK, but some tests were skipped!\nTests: 9, Assertions: 12, Skipped: 1.\n";

        $result = $this->runScript($this->fixtureFile('over.log', $over));

        self::assertSame(3, $result['exit'], 'over-counting is drift and must be loud');
        self::assertSame([], $result['lines']);
        self::assertStringContainsString('No tests executed!', $result['stderr']);
    }

    // ---------------------------------------------------------------------------------
    // helpers
    // ---------------------------------------------------------------------------------

    private function fixtureFile(string $name, ?string $contents = null): string
    {
        $path = $this->tmpDir . '/' . $name;
        file_put_contents($path, ($contents ?? self::FIXTURE) . "\n");

        return $path;
    }

    /**
     * Writes a throwaway test class whose `setUpBeforeClass()` skips, which is how PHPUnit
     * emits a testSuiteSkipped event. Returns its path.
     */
    private function writeSuiteSkipProbe(): string
    {
        $path = $this->tmpDir . '/S345SuiteSkipProbeTest.php';

        file_put_contents($path, <<<'PROBE'
            <?php

            declare(strict_types=1);

            namespace Phlix\Tests\Scratch;

            use PHPUnit\Framework\TestCase;

            final class S345SuiteSkipProbeTest extends TestCase
            {
                public static function setUpBeforeClass(): void
                {
                    self::markTestSkipped('S345 probe: the whole suite is skipped');
                }

                public function test_never_runs(): void
                {
                    self::assertTrue(true);
                }
            }
            PROBE);

        return $path;
    }

    /**
     * @param list<string> $args
     */
    private function runRealPhpunit(array $args): string
    {
        $root = realpath(self::REPO);
        self::assertIsString($root);
        self::assertFileExists($root . '/vendor/bin/phpunit');

        $command = 'cd ' . escapeshellarg($root) . ' && '
            . escapeshellarg(PHP_BINARY) . ' ' . escapeshellarg($root . '/vendor/bin/phpunit')
            . ' -c ' . escapeshellarg($root . '/phpunit.xml')
            . ' --no-coverage --colors=never';

        foreach ($args as $argument) {
            $command .= ' ' . escapeshellarg($argument);
        }

        $out = $this->tmpDir . '/phpunit-run.txt';
        exec($command . ' > ' . escapeshellarg($out) . ' 2>&1');

        $output = (string) file_get_contents($out);
        @unlink($out);

        self::assertStringContainsString(
            'PHPUnit 10.5',
            $output,
            "the real phpunit binary produced no recognisable output, so nothing below is measuring "
            . "anything:\n" . $output,
        );

        return $output;
    }

    /**
     * Finds a locale installed on this box whose collation orders C_ORDER_PAIR the other
     * way round, DERIVED by running `sort` rather than hard-coded.
     */
    private function localeWhoseCollationDiffersFromC(): ?string
    {
        $file = $this->tmpDir . '/collate.txt';
        file_put_contents($file, self::C_ORDER_PAIR[1] . "\n" . self::C_ORDER_PAIR[0] . "\n");

        $locales = [];
        exec('locale -a 2>/dev/null', $locales);

        foreach ($locales as $locale) {
            if (!str_contains(strtolower($locale), 'utf')) {
                continue;
            }

            $sorted = [];
            exec('LC_ALL=' . escapeshellarg($locale) . ' sort ' . escapeshellarg($file) . ' 2>/dev/null', $sorted);

            if (array_values($sorted) !== self::C_ORDER_PAIR) {
                @unlink($file);

                return $locale;
            }
        }

        @unlink($file);

        return null;
    }

    /**
     * @param array<string, string> $env
     *
     * @return array{exit: int, stdout: string, lines: list<string>, stderr: string}
     */
    private function runScript(string $input, array $env = []): array
    {
        $stdoutFile = $this->tmpDir . '/stdout.txt';
        $stderrFile = $this->tmpDir . '/stderr.txt';

        $prefix = '';
        foreach ($env as $name => $value) {
            $prefix .= $name . '=' . escapeshellarg($value) . ' ';
        }

        $exit = 0;
        exec(
            $prefix . escapeshellarg(self::SCRIPT) . ' ' . escapeshellarg($input)
            . ' > ' . escapeshellarg($stdoutFile) . ' 2> ' . escapeshellarg($stderrFile),
            $ignored,
            $exit,
        );

        $stdout = (string) file_get_contents($stdoutFile);

        return [
            'exit' => $exit,
            'stdout' => $stdout,
            // Deliberately NOT filtered: a blank line is a set member for `comm`, so it must
            // be able to fail an assertion rather than be dropped on the way in.
            'lines' => $stdout === '' ? [] : explode("\n", rtrim($stdout, "\n")),
            'stderr' => (string) file_get_contents($stderrFile),
        ];
    }
}
