<?php

declare(strict_types=1);

namespace Phlix\Tests\Unit\Support;

use DOMDocument;
use PHPUnit\Framework\TestCase;
use Symfony\Component\Yaml\Yaml;

/**
 * S345 — a skip set must be comparable BY NAME, not by count.
 *
 * ## What was actually wrong, measured rather than asserted
 *
 * `phpunit.xml` displayed details for deprecations, warnings and errors, and NOT for
 * skipped tests, and no workflow passed the CLI flag either. So the only thing any run
 * of this suite published about its skips was the number in
 * `Tests: N, ..., Skipped: M.`. Measured on master run `32027697809`
 * (head `e5099b88`): the log says `Skipped: 3` and contains ZERO
 * `There were N skipped tests:` sections.
 *
 * A count cannot distinguish the three things that move it —
 *
 *   1. a test STARTED skipping (a real regression),
 *   2. a conditionally-skipped test turned into a FAILURE (it left the skip set),
 *   3. a test DISAPPEARED (deleted, renamed, or no longer collected),
 *
 * — and it drifts on its own between runs, because this repo has legitimate
 * environment-dependent skips: CI reports 3 where a box with no MySQL, no Chromium and
 * no mysqldump reports ~259. Worse, 1 and 2 can happen together and leave the count
 * UNMOVED. Two audits were forced to record skip movement as "unproven" for exactly
 * this reason. A NAME SET compared with `comm` separates all three.
 *
 * ## Why half of this file drives the REAL phpunit binary
 *
 * The first cut of this test pinned the script against a hand-written constant that
 * mirrored PHPUnit's output. That fixture was, by construction, unable to notice that
 * the real thing differs — and it differed twice:
 *
 *   * `--testdox` can NEVER name a skipped test. PHPUnit builds the default result
 *     printer for a testdox run with `$displayDetailsOnSkippedTests` hardcoded `false`
 *     (`vendor/phpunit/phpunit/src/TextUI/Output/Facade.php:204-221`), so the config
 *     value is not consulted at all. `syncplay-e2e.yml` passed `--testdox`; the
 *     fixture could not see it, and the script blamed `phpunit.xml` for it.
 *   * a skipped test SUITE is counted in the same `Skipped: N` (`SummaryPrinter.php:106`)
 *     but named under a DIFFERENT header, with no `::` in its entries — and a run in
 *     which every suite skipped prints `No tests executed!` and no `Tests:` line at all.
 *
 * So the shapes are now RE-DERIVED from `./vendor/bin/phpunit` in a subprocess
 * (`tests/Unit/Admin/BackupManagerTest.php` skips exactly one test unconditionally and
 * runs in ~0.03 s; the suite-skip shape is generated by writing a throwaway test class
 * with a skipping `setUpBeforeClass()`). Hand-written fixtures are kept ONLY for the
 * shapes the binary cannot produce here: a `gh run view --log` prefix, a whole-workflow
 * log containing several runs, and format DRIFT.
 *
 * ## What this test pins, and what it deliberately does not
 *
 * Two halves, and both must hold or the guarantee is gone:
 *
 *   * `phpunit.xml` carries `displayDetailsOnSkippedTests="true"` — checked against the
 *     PARSED document, not the file's text, so commenting the root element's attribute
 *     out cannot pass. Deleting it is otherwise SILENT: every run stays green and every
 *     count keeps being reported, and the loss shows up only the next time somebody
 *     needs a name set and no longer has one.
 *   * `scripts/skipped-test-names.sh` still turns that output into a sorted,
 *     `comm`-ready set — and each refusal path names the cause its own arithmetic
 *     supports, for every input measured here, because a parser that quietly matches
 *     NOTHING reads as a pass and a WRONG diagnosis is worse than none. That is a set of
 *     pinned inputs, NOT a proof over all inputs: the script's denominators are
 *     input-wide sums, so a multi-run log can still net one run's shortfall against
 *     another's surplus (see KNOWN LIMITS in `scripts/skipped-test-names.sh`, and the
 *     per-run-segmentation follow-up it points at).
 *
 * It does NOT try to defend the script against being rewritten, and it does not assert
 * a skip COUNT anywhere. Asserting a count here would reintroduce the exact measure the
 * step exists to replace.
 */
final class SkippedTestNameReportingTest extends TestCase
{
    private const REPO = __DIR__ . '/../../..';

    private const SCRIPT = self::REPO . '/scripts/skipped-test-names.sh';

    private const CONFIG = self::REPO . '/phpunit.xml';

    /**
     * A test file with exactly ONE skip, taken unconditionally in the method body
     * (`BackupManagerTest.php:30`), so the real-binary expectations below do not depend
     * on MySQL, Chromium, FFI or anything else about the box.
     */
    private const REAL_TEST_FILE = 'tests/Unit/Admin/BackupManagerTest.php';

    private const REAL_SKIPPED_NAME = 'Phlix\Tests\Unit\Admin\BackupManagerTest::testCreateBackupGeneratesIdAndPath';

    /**
     * A minimal but realistic PHPUnit 10.5 tail: a first list (so the `--` separator is
     * present, as it is in a real red run), the skipped-details list, and the summary.
     * Kept for the shapes the real binary cannot produce here — the `gh` log prefix and
     * deliberate format drift.
     */
    private const FIXTURE = <<<'OUT'
        PHPUnit 10.5.64 by Sebastian Bergmann and contributors.

        Runtime:       PHP 8.3.6
        Configuration: /repo/phpunit.xml

        There was 1 failure:

        1) Phlix\Tests\Unit\Zeta\ZetaTest::testUnrelated
        Failed asserting that false is true.

        --

        There were 4 skipped tests:

        1) Phlix\Tests\Integration\Media\MusicDtoTest::testColumnIsChar36
        No MySQL on 127.0.0.1:3306

        /repo/tests/Support/Database/RequiresRealDatabase.php:41

        2) Phlix\Tests\E2E\Media\Transcoding\Fmp4HlsPlaybackE2ETest::testRemovingTheExtXMapBreaksPlayback
        no Chrome/Chromium binary

        3) Phlix\Tests\Unit\Admin\BackupManagerTest::testCreateBackupGeneratesIdAndPath with data set "a b"
        createBackup requires mysqldump

        4) Phlix\Tests\Unit\Alpha\AlphaTest::testGamma
        FFI is not available on this system

        FAILURES!
        Tests: 9, Assertions: 12, Failures: 1, Skipped: 4.
        OUT;

    /**
     * Master's own pre-S345 shape: a skip COUNT and no detail list to read it from.
     * Shared by every test about the diagnosis of a missing list, so they cannot drift
     * apart from each other.
     */
    private const COUNT_ONLY = "PHPUnit 10.5.64\n\nOK, but there were issues!\nTests: 9, Assertions: 12, Skipped: 4.\n";

    /** @var list<string> */
    private const EXPECTED_NAMES = [
        'Phlix\Tests\E2E\Media\Transcoding\Fmp4HlsPlaybackE2ETest::testRemovingTheExtXMapBreaksPlayback',
        'Phlix\Tests\Integration\Media\MusicDtoTest::testColumnIsChar36',
        'Phlix\Tests\Unit\Admin\BackupManagerTest::testCreateBackupGeneratesIdAndPath with data set "a b"',
        'Phlix\Tests\Unit\Alpha\AlphaTest::testGamma',
    ];

    /**
     * Two names whose byte order (`LC_ALL=C`) is the REVERSE of their order under a
     * UTF-8 collation, because `\` (0x5C) sorts after `B` (0x42) byte-wise while a
     * locale-aware sort ignores the punctuation at the first level. GNU `comm` compares
     * byte-wise, so the C order is the only one it accepts.
     */
    private const C_ORDER_PAIR = [
        'Phlix\Tests\UnitB\ATest::testA',
        'Phlix\Tests\Unit\Admin\ZTest::testA',
    ];

    private string $tmpDir = '';

    protected function setUp(): void
    {
        $dir = sys_get_temp_dir() . '/phlix-s345-' . bin2hex(random_bytes(6));
        self::assertTrue(mkdir($dir, 0o700), 'could not create the fixture directory');
        $this->tmpDir = $dir;
    }

    protected function tearDown(): void
    {
        if ($this->tmpDir === '') {
            return;
        }

        foreach ((glob($this->tmpDir . '/*') ?: []) as $file) {
            @unlink($file);
        }

        @rmdir($this->tmpDir);
        $this->tmpDir = '';
    }

    public function test_phpunit_xml_still_asks_for_skipped_test_names(): void
    {
        $document = new DOMDocument();
        self::assertTrue(
            $document->load(self::CONFIG),
            'phpunit.xml could not be parsed.',
        );

        $root = $document->documentElement;
        self::assertNotNull($root, 'phpunit.xml has no root element.');

        self::assertSame(
            'true',
            $root->getAttribute('displayDetailsOnSkippedTests'),
            'phpunit.xml has lost displayDetailsOnSkippedTests="true" (S345). Without it PHPUnit '
            . 'prints only the skip COUNT, and a count cannot distinguish a test that started '
            . 'skipping from one that turned into a failure from one that disappeared. Removing it '
            . 'is otherwise SILENT — every run stays green. Restore the attribute; do not delete '
            . 'this test.',
        );
    }

    public function test_the_extraction_script_is_present_and_executable(): void
    {
        self::assertFileExists(
            self::SCRIPT,
            'scripts/skipped-test-names.sh is gone. It is the documented way to turn a run into a '
            . '`comm`-ready name set (README, "Comparing skip sets between two runs").',
        );
        self::assertTrue(
            is_executable(self::SCRIPT),
            'scripts/skipped-test-names.sh has lost its executable bit, so the documented '
            . '`| scripts/skipped-test-names.sh` pipeline no longer runs.',
        );
    }

    public function test_the_readme_documents_the_comm_ready_one_liner(): void
    {
        $readme = (string) file_get_contents(self::REPO . '/README.md');

        self::assertStringContainsString(
            'scripts/skipped-test-names.sh',
            $readme,
            'README.md no longer points at the extraction script. A one-liner that lives only in a '
            . 'PR description is not documentation.',
        );
        self::assertStringContainsString(
            'comm -3',
            $readme,
            'README.md no longer shows the `comm` comparison, which is the whole point of producing '
            . 'a name set rather than a count.',
        );
    }

    /**
     * No workflow may pass `--testdox` to PHPUnit, because such a run adds to
     * `Skipped: N` and can never name those skips (Facade.php:204-221) — so a
     * whole-workflow log stops being comparable. `syncplay-e2e.yml` used to.
     *
     * Re-derived from the workflow DIRECTORY, never from a list of file names, and
     * round 2 of this step's review found two ways the first version of that
     * re-derivation could be defeated while staying green: a `.yaml` extension (GitHub
     * Actions accepts both) and a `\`-continuation line (the flag on its own line). Both
     * are now pinned by their own fixtures below — {@see
     * test_the_testdox_ban_discovers_yaml_as_well_as_yml_workflows} and {@see
     * test_the_testdox_ban_sees_a_flag_on_a_shell_continuation_line} — because the real
     * directory cannot exhibit either shape without reintroducing the defect.
     */
    public function test_no_workflow_invokes_phpunit_with_testdox(): void
    {
        $files = $this->workflowFiles(self::REPO . '/.github/workflows');

        // Anti-vacuity: this guard is a search over these files, so an empty or shrunken
        // list must fail rather than pass.
        self::assertGreaterThanOrEqual(
            6,
            count($files),
            'the workflow directory looks empty or the glob stopped matching — this guard '
            . 'would then prove nothing: ' . implode(', ', array_map('basename', $files)),
        );

        $offenders = [];

        foreach ($files as $file) {
            $offenders = [...$offenders, ...$this->testdoxOffenders(
                (string) file_get_contents($file),
                basename($file),
            )];
        }

        self::assertSame(
            [],
            $offenders,
            "A workflow passes --testdox to PHPUnit (S345). PHPUnit constructs the default result\n"
            . "printer with \$displayDetailsOnSkippedTests hardcoded FALSE for testdox runs\n"
            . "(vendor/phpunit/phpunit/src/TextUI/Output/Facade.php:204-221), so that step counts its\n"
            . "skips in `Skipped: N` and can NEVER name them — neither phpunit.xml's\n"
            . "displayDetailsOnSkippedTests=\"true\" nor --display-skipped can fix it. It also makes a\n"
            . "whole-run `gh run view --log` un-comparable, because the count and the name set no\n"
            . "longer agree. Drop the flag:\n" . implode("\n", $offenders),
        );
    }

    /**
     * Fixture for the first hole: `glob('*.yml')` cannot see `new-suite.yaml`, and GitHub
     * Actions runs both extensions. Measured before the fix: adding such a file with
     * `--testdox` in it left the guard above green.
     */
    public function test_the_testdox_ban_discovers_yaml_as_well_as_yml_workflows(): void
    {
        file_put_contents($this->tmpDir . '/a.yml', "on: push\njobs: {}\n");
        file_put_contents($this->tmpDir . '/b.yaml', "on: push\njobs: {}\n");
        file_put_contents($this->tmpDir . '/c.txt', 'not a workflow');

        self::assertSame(
            ['a.yml', 'b.yaml'],
            array_map('basename', $this->workflowFiles($this->tmpDir)),
            'the workflow discovery must cover BOTH extensions GitHub Actions accepts, or a '
            . '`.yaml` workflow can pass --testdox invisibly (S345 round-2 finding 2a)',
        );
    }

    /**
     * Fixture for the second hole: the flag on a `\`-continuation line of a `run: |`
     * block. Measured before the fix: rewriting the syncplay step that way left the guard
     * green, because the per-line check needed `phpunit` and `--testdox` on ONE line.
     *
     * The third case is the negative control that keeps the rule from being noisy:
     * `--testdox-html`/`--testdox-text` are logging targets and do NOT put PHPUnit into
     * testdox output mode (Cli/Builder.php:851-862 sets `$testdoxOutput` only for
     * `--testdox`), so a substring match would fire on them wrongly.
     */
    public function test_the_testdox_ban_sees_a_flag_on_a_shell_continuation_line(): void
    {
        $wrapped = <<<'YAML'
            on: push
            jobs:
              e2e:
                steps:
                  - name: Run E2E tests
                    run: |
                      ./vendor/bin/phpunit tests/E2E/Foo.php \
                        --testdox \
                        --colors=never
            YAML;

        self::assertNotSame(
            [],
            $this->testdoxOffenders($wrapped, 'wrapped.yml'),
            'a `\`-continuation must be folded before matching, or wrapping the command hides '
            . 'the flag from this guard (S345 round-2 finding 2b)',
        );

        $sameLine = str_replace(" \\\n    ", ' ', $wrapped);
        self::assertNotSame(
            [],
            $this->testdoxOffenders($sameLine, 'oneline.yml'),
            'the same command on one line must still be caught — this is the control that shows '
            . 'the fixture above is not passing for an unrelated reason',
        );

        $clean = <<<'YAML'
            on: push
            jobs:
              e2e:
                steps:
                  - name: Run E2E tests
                    # --testdox is deliberately NOT passed to phpunit here (S345)
                    run: |
                      ./vendor/bin/phpunit tests/E2E/Foo.php \
                        --testdox-html build/testdox.html \
                        --colors=never   # a # inside a comment, and "a # in a quote"
            YAML;

        self::assertSame(
            [],
            $this->testdoxOffenders($clean, 'clean.yml'),
            'the ban must not fire on prose in a comment, nor on --testdox-html/--testdox-text, '
            . 'which do not put PHPUnit into testdox OUTPUT mode. A noisy rule gets deleted.',
        );
    }

    /**
     * The invocation-site claim made by `phpunit.xml`, this script's header, `README.md`
     * and `CHANGELOG.md` — "five places" — RE-DERIVED, because round-1 found the number
     * wrong and round-2 found the line numbers it cited stale by the same commit that
     * wrote them. Line numbers are gone from those documents for that reason; this test
     * is what keeps the remaining claim honest.
     *
     * The four workflow sites are derived from the parsed `run:` scalars. The fifth is the
     * prober, which is a PHP `exec` rather than a workflow step, so it is asserted
     * separately — including the property that makes it an exception rather than a bug
     * (its output is captured into a variable, never echoed).
     */
    public function test_the_documented_invocation_sites_are_still_the_real_ones(): void
    {
        $perWorkflow = [];

        foreach ($this->workflowFiles(self::REPO . '/.github/workflows') as $file) {
            foreach ($this->runScalars((string) file_get_contents($file)) as $run) {
                foreach ($this->logicalCommandLines($run) as $line) {
                    if (str_contains($line, 'vendor/bin/phpunit')) {
                        $perWorkflow[basename($file)] = ($perWorkflow[basename($file)] ?? 0) + 1;
                    }
                }
            }
        }

        ksort($perWorkflow);

        self::assertSame(
            [
                'phpunit.yml' => 2,
                'syncplay-e2e.yml' => 2,
            ],
            $perWorkflow,
            'the set of workflow steps that invoke PHPUnit has changed. Four of the five '
            . '"places" documented in phpunit.xml, scripts/skipped-test-names.sh, README.md and '
            . 'CHANGELOG.md are these; update those documents (by FILE, not by line number) and '
            . 'this expectation together. A new invocation is exactly the case the config '
            . 'attribute exists to cover, so check it does not pass --testdox either.',
        );

        $prober = (string) file_get_contents(self::REPO . '/scripts/assertion-escape-audit.php');

        self::assertStringContainsString(
            'vendor/bin/phpunit',
            $prober,
            'the fifth documented invocation site (the assertion-escape prober) no longer runs '
            . 'PHPUnit — update the "five places" claim in the four documents that make it',
        );
        self::assertMatchesRegularExpression(
            '/exec\(\$command[^;]*\$output/',
            $prober,
            'the prober no longer captures PHPUnit\'s output into a variable. If it echoes it '
            . 'now, it is no longer an exception to the mechanism and the documents that call it '
            . 'one are wrong.',
        );
        self::assertDoesNotMatchRegularExpression(
            '/\b(passthru|system)\s*\(/',
            $prober,
            'the prober now writes a subprocess\'s output straight to its own stdout, so the '
            . '"its output never leaves the process" exception documented in four places may no '
            . 'longer hold — re-derive it before trusting those documents',
        );
    }

    // ---------------------------------------------------------------------------------
    // Shapes RE-DERIVED from the real phpunit binary
    // ---------------------------------------------------------------------------------

    public function test_a_real_run_yields_the_skipped_name_through_the_script(): void
    {
        $output = $this->runRealPhpunit([self::REAL_TEST_FILE]);

        $this->assertTheFixtureStillSkipsExactlyOneTest($output);

        self::assertStringContainsString(
            'skipped test:',
            $output,
            'the real binary counted a skip and printed no skipped-details list for it, so '
            . 'phpunit.xml is not reaching this invocation (the fixture premise is asserted '
            . 'separately above, so it is not the explanation here)',
        );

        $result = $this->runScript($this->fixtureFile('real.log', $output));

        self::assertSame(0, $result['exit'], $result['stderr'] . "\n--- phpunit output ---\n" . $output);
        self::assertSame([self::REAL_SKIPPED_NAME], $result['lines'], $result['stderr']);
    }

    public function test_a_real_testdox_run_is_reported_as_testdox_and_never_blamed_on_phpunit_xml(): void
    {
        $output = $this->runRealPhpunit([self::REAL_TEST_FILE, '--testdox']);

        // The premise, re-derived rather than assumed: testdox counts the skip and never names it.
        $this->assertTheFixtureStillSkipsExactlyOneTest($output);
        self::assertStringNotContainsString(
            'skipped test:',
            $output,
            'testdox now prints a skipped-details list — Facade.php changed, so the exit-5 '
            . 'diagnosis needs re-deriving',
        );

        $result = $this->runScript($this->fixtureFile('testdox.log', $output));

        self::assertSame(
            5,
            $result['exit'],
            "a --testdox run must be reported AS a testdox run (exit 5). Exit 4 here would be a\n"
            . "FALSE diagnosis — it blames phpunit.xml, which is correct, and sends the reader to\n"
            . "change a config that cannot affect this. stderr was:\n" . $result['stderr'],
        );
        self::assertSame([], $result['lines'], 'a partial set must not be written');
        self::assertStringContainsString('--testdox', $result['stderr']);
        self::assertStringContainsString('Facade.php:204-221', $result['stderr']);
        self::assertStringNotContainsString(
            'has lost displayDetailsOnSkippedTests',
            $result['stderr'],
            'the testdox case must NOT be diagnosed as a missing attribute — the attribute is '
            . 'present and PHPUnit ignores it on that path',
        );
    }

    public function test_a_real_skipped_test_suite_is_named_rather_than_counted(): void
    {
        $probe = $this->writeSuiteSkipProbe();

        // Suite skip ALONE: PHPUnit prints `No tests executed!` and NO `Tests:` line, so the
        // `Skipped: N` cross-check does not exist for this shape.
        $alone = $this->runRealPhpunit([$probe]);

        // The PROBE's premise first, and separately: `No tests executed!` with no totals line
        // is what a whole-suite skip looks like, and it does not depend on phpunit.xml. If
        // this is what broke, the list assertion below would blame the config for it.
        self::assertStringContainsString(
            'No tests executed!',
            $alone,
            'the probe class no longer skips its whole suite (markTestSkipped() in '
            . 'setUpBeforeClass()), so nothing below is measuring the suite-skip shape — '
            . 'regenerate the probe, do not touch phpunit.xml',
        );
        self::assertStringNotContainsString('Tests: ', $alone, 'this shape is supposed to publish no totals line');

        self::assertStringContainsString(
            'skipped test suite:',
            $alone,
            'a suite really was skipped (asserted above) and the real binary named none of '
            . 'them, so displayDetailsOnSkippedTests is not reaching this invocation',
        );

        $result = $this->runScript($this->fixtureFile('suite-alone.log', $alone));
        self::assertSame(0, $result['exit'], $result['stderr'] . "\n--- phpunit output ---\n" . $alone);
        self::assertSame(['SUITE:Phlix\Tests\Scratch\S345SuiteSkipProbeTest'], $result['lines'], $result['stderr']);

        // Suite skip PLUS a test skip: one `Skipped: 2`, two different headers.
        $mixed = $this->runRealPhpunit([$probe, self::REAL_TEST_FILE]);
        self::assertStringContainsString('Skipped: 2', $mixed, 'a suite skip must count towards Skipped: N');

        $result = $this->runScript($this->fixtureFile('suite-mixed.log', $mixed));
        self::assertSame(
            0,
            $result['exit'],
            "a skipped SUITE is part of `Skipped: N` but is named under its own header, so blaming\n"
            . "the config (exit 4) or the parser (exit 3) for it is a FALSE diagnosis. stderr:\n"
            . $result['stderr'] . "\n--- phpunit output ---\n" . $mixed,
        );
        self::assertSame(
            [
                self::REAL_SKIPPED_NAME,
                'SUITE:Phlix\Tests\Scratch\S345SuiteSkipProbeTest',
            ],
            $result['lines'],
            $result['stderr'],
        );
    }

    public function test_a_real_colorized_run_is_parsed_rather_than_refused(): void
    {
        // `colors="true"` in phpunit.xml means COLOR_AUTO, so a pipe is never colorized in
        // practice — but a human running `--colors=always` and pasting the log must not be told
        // "this is not a PHPUnit run". The summary lines are the ANSI-wrapped ones, which is
        // exactly what defeats the positive control if escapes are not stripped.
        $output = $this->runRealPhpunit([self::REAL_TEST_FILE, '--colors=always']);

        $this->assertTheFixtureStillSkipsExactlyOneTest($output);

        self::assertStringContainsString(
            "\033[",
            $output,
            'the run produced no ANSI escapes, so this test would not be measuring anything',
        );

        $result = $this->runScript($this->fixtureFile('colors.log', $output));

        self::assertSame(
            0,
            $result['exit'],
            'a colorized run parses correctly apart from the escapes, so refusing it as "not a '
            . "PHPUnit run\" would be a false diagnosis. stderr:\n" . $result['stderr'],
        );
        self::assertSame([self::REAL_SKIPPED_NAME], $result['lines'], $result['stderr']);
    }

    public function test_a_truncated_write_is_refused_instead_of_handing_comm_a_short_set(): void
    {
        // `sort`'s exit status must be checked: a failing write (ENOSPC here, SIGPIPE in a
        // pipeline) otherwise yields a TRUNCATED set and exit 0 — the precise "quietly wrong
        // set handed to comm" outcome the whole exit contract exists to prevent.
        $output = $this->runRealPhpunit([self::REAL_TEST_FILE]);
        $input = $this->fixtureFile('write-fail.log', $output);

        if (!is_writable('/dev/full')) {
            // No always-full device on this box, so the failure cannot be provoked; pin the
            // mechanism textually rather than reporting a pass that measured nothing.
            self::assertStringContainsString(
                'write_status',
                // CODE only: a header comment must not be able to satisfy a fallback that
                // stands in for a measurement (S345 round-2 finding 4, same shape).
                $this->scriptCode(),
                '/dev/full is unavailable, so the truncated-write path cannot be exercised here; '
                . "the script must still check the status of its `sort` pipeline",
            );

            return;
        }

        $stderrFile = $this->tmpDir . '/full-stderr.txt';
        $exit = 0;
        exec(
            escapeshellarg(self::SCRIPT) . ' ' . escapeshellarg($input)
            . ' > /dev/full 2> ' . escapeshellarg($stderrFile),
            $ignored,
            $exit,
        );

        self::assertSame(6, $exit, (string) file_get_contents($stderrFile));
        self::assertStringContainsString(
            'stdout is TRUNCATED',
            (string) file_get_contents($stderrFile),
        );
    }

    // ---------------------------------------------------------------------------------
    // Hand-written shapes the binary cannot produce here
    // ---------------------------------------------------------------------------------

    public function test_it_emits_the_sorted_name_set_and_nothing_else(): void
    {
        $result = $this->runScript($this->fixtureFile('run.log'));

        self::assertSame(0, $result['exit'], $result['stderr']);
        self::assertSame(self::EXPECTED_NAMES, $result['lines'], $result['stderr']);

        // "nothing else", asserted on the RAW bytes rather than on a filtered array: a blank
        // line is a set member as far as `comm` is concerned, and leading whitespace changes
        // the byte comparison.
        self::assertSame(
            implode("\n", self::EXPECTED_NAMES) . "\n",
            $result['stdout'],
            'stdout must be exactly the set, newline-terminated, with no blank or indented lines',
        );

        // Sortedness is delivered by the assertion ABOVE, because the fixture lists the names
        // in a different order from the sorted one. Pin that premise instead of re-sorting an
        // already-sorted array, which cannot fail.
        $asPrinted = [];
        preg_match_all('/^[0-9]+\) (\S+::\S.*)$/m', self::FIXTURE, $matches);
        foreach ($matches[1] as $name) {
            $asPrinted[] = trim($name);
        }

        self::assertNotSame(
            self::EXPECTED_NAMES,
            array_slice($asPrinted, 1),
            'the fixture must print the names in an UNSORTED order, or the assertion above cannot '
            . 'prove that the script sorts',
        );
    }

    public function test_a_class_name_containing_digits_is_not_dropped(): void
    {
        // The bug the denominator caught: `Fmp4Hls…` and `OAuth2…` were silently lost.
        self::assertContains(
            'Phlix\Tests\E2E\Media\Transcoding\Fmp4HlsPlaybackE2ETest::testRemovingTheExtXMapBreaksPlayback',
            $this->runScript($this->fixtureFile('run.log'))['lines'],
        );
    }

    public function test_it_reads_a_gh_run_view_log_with_its_job_step_timestamp_prefix(): void
    {
        $prefixed = [];
        foreach (explode("\n", self::FIXTURE) as $line) {
            $prefixed[] = "PHPUnit Test Suite\tRun PHPUnit tests\t2026-08-20T06:22:33.1234567Z " . $line;
        }

        $result = $this->runScript($this->fixtureFile('gh.log', implode("\n", $prefixed)));

        self::assertSame(0, $result['exit'], $result['stderr']);
        self::assertSame(self::EXPECTED_NAMES, $result['lines'], $result['stderr']);
    }

    public function test_the_same_name_from_two_jobs_is_emitted_once(): void
    {
        // A whole-workflow log: tests/Unit/Server/ skips appear in both `test` and
        // `test-server`. Without `sort -u` the set has a duplicate line and `comm` reports a
        // difference that does not exist.
        $run = "PHPUnit 10.5.64\n\nThere was 1 skipped test:\n\n"
            . '1) ' . self::REAL_SKIPPED_NAME . "\nreason\n\n"
            . "OK, but some tests were skipped!\nTests: 4, Assertions: 4, Skipped: 1.\n";

        $result = $this->runScript($this->fixtureFile('two-jobs.log', $run . "\n" . $run));

        self::assertSame(0, $result['exit'], $result['stderr']);
        self::assertSame([self::REAL_SKIPPED_NAME], $result['lines'], $result['stderr']);
    }

    public function test_the_set_is_ordered_BYTE_wise_so_comm_accepts_it(): void
    {
        $run = "PHPUnit 10.5.64\n\nThere were 2 skipped tests:\n\n"
            . '1) ' . self::C_ORDER_PAIR[1] . "\nreason\n\n"
            . '2) ' . self::C_ORDER_PAIR[0] . "\nreason\n\n"
            . "OK, but some tests were skipped!\nTests: 4, Assertions: 4, Skipped: 2.\n";

        $file = $this->fixtureFile('locale.log', $run);
        $utf8Locale = $this->localeWhoseCollationDiffersFromC();

        // Run the script under a locale whose collation would reorder these two names, so that
        // dropping the script's own `LC_ALL=C` changes the output. `comm` compares byte-wise
        // (GNU coreutils 9.4: it rejects a locale-ordered file with "is not in sorted order").
        $result = $this->runScript($file, $utf8Locale === null ? [] : ['LC_ALL' => $utf8Locale]);

        self::assertSame(0, $result['exit'], $result['stderr']);
        self::assertSame(
            self::C_ORDER_PAIR,
            $result['lines'],
            'the set must be in BYTE order (LC_ALL=C), whatever locale the caller runs under, '
            . 'or GNU `comm` refuses it as unsorted. Ambient locale for this run: '
            . ($utf8Locale ?? 'none available that collates differently from C'),
        );

        if ($utf8Locale === null) {
            // No locale on this box reorders the pair, so the behavioural check above cannot
            // fail. Fall back to pinning the mechanism textually rather than reporting a pass
            // that proves nothing — and pin it against the script's CODE only. The literal
            // `LC_ALL=C sort -u` also appears in the script's header comment (the copy-paste
            // one-liner), so a str_contains over the whole file could be satisfied by the very
            // prose this test exists to verify, and would pass with the real command mutated.
            self::assertStringContainsString(
                'LC_ALL=C sort -u',
                $this->scriptCode(),
                'no locale on this box collates differently from C, so the byte-order property '
                . 'cannot be measured here; the script must still pin LC_ALL=C explicitly in its '
                . 'CODE (the header comment does not count)',
            );
        }
    }

    public function test_input_that_is_not_a_phpunit_run_is_refused_rather_than_reported_as_empty(): void
    {
        $result = $this->runScript($this->fixtureFile('junk.log', "hello\nworld\n"));

        self::assertSame(2, $result['exit'], 'a parser fed the wrong input must not read as "no skips"');
        self::assertSame([], $result['lines']);
        self::assertStringContainsString('no PHPUnit result summary', $result['stderr']);
    }

    public function test_a_run_that_skipped_tests_but_printed_no_names_is_refused(): void
    {
        // Exactly master's shape before S345: a count, and no detail list to read it from.
        $result = $this->runScript($this->fixtureFile('countonly.log', self::COUNT_ONLY));

        self::assertSame(4, $result['exit'], 'a missing displayDetailsOnSkippedTests must be loud, not empty');
        self::assertSame([], $result['lines']);
        self::assertStringContainsString('displayDetailsOnSkippedTests', $result['stderr']);
    }

    public function test_a_run_with_no_skips_at_all_is_an_empty_set_and_a_success(): void
    {
        $clean = "PHPUnit 10.5.64\n\nOK (9 tests, 12 assertions)\n";

        $result = $this->runScript($this->fixtureFile('clean.log', $clean));

        self::assertSame(0, $result['exit'], $result['stderr']);
        self::assertSame([], $result['lines']);
    }

    public function test_extraction_that_disagrees_with_phpunits_own_count_is_refused(): void
    {
        // One name mangled: PHPUnit still declares 4, only 3 are recoverable.
        $drifted = str_replace(
            '4) Phlix\Tests\Unit\Alpha\AlphaTest::testGamma',
            '4) something the parser cannot read',
            self::FIXTURE,
        );

        $result = $this->runScript($this->fixtureFile('drift.log', $drifted));

        self::assertSame(3, $result['exit'], 'a partial extraction must not be handed to `comm` as if complete');
        self::assertSame([], $result['lines']);
        self::assertStringContainsString('entry format has drifted', $result['stderr']);
    }

    /**
     * The branch findings 1 and 2 both fired and which nothing reached: the summaries
     * report MORE skips than the detail lists declared, without testdox output to explain
     * it and with a non-empty list (so neither exit 5 nor exit 4 applies). The shape is
     * real — a whole-workflow log in which one job did not load `phpunit.xml`.
     */
    public function test_a_list_that_names_fewer_skips_than_the_summary_is_refused_as_partial(): void
    {
        $partial = "PHPUnit 10.5.64\n\nThere was 1 skipped test:\n\n"
            . "1) Phlix\Tests\Unit\Alpha\AlphaTest::testGamma\nreason\n\n"
            . "OK, but some tests were skipped!\nTests: 9, Assertions: 12, Skipped: 3.\n";

        $result = $this->runScript($this->fixtureFile('partial.log', $partial));

        self::assertSame(3, $result['exit'], 'a set missing 2 of 3 names must not be handed to `comm`');
        self::assertSame([], $result['lines'], 'a PARTIAL set must not be written');
        self::assertStringContainsString('2 name(s) are missing', $result['stderr']);
    }

    /**
     * The mirror image, and the reason the `No tests executed!` allowance is conditional:
     * MORE declared than summarised, with no run reporting `No tests executed!`, can only
     * be the parser over-counting.
     */
    public function test_a_list_that_names_more_skips_than_the_summary_is_refused_as_drift(): void
    {
        $over = "PHPUnit 10.5.64\n\nThere were 2 skipped tests:\n\n"
            . "1) Phlix\Tests\Unit\Alpha\AlphaTest::testGamma\nreason\n\n"
            . "2) Phlix\Tests\Unit\Beta\BetaTest::testDelta\nreason\n\n"
            . "OK, but some tests were skipped!\nTests: 9, Assertions: 12, Skipped: 1.\n";

        $result = $this->runScript($this->fixtureFile('over.log', $over));

        self::assertSame(3, $result['exit'], 'over-counting is drift and must be loud');
        self::assertSame([], $result['lines']);
        self::assertStringContainsString('No tests executed!', $result['stderr']);
    }

    /**
     * Round-2 finding 1, measured: exit 5 used to be gated on the mere PRESENCE of
     * testdox-looking output, so a count-only run that shared a log with a ZERO-skip
     * testdox run was told "Do NOT change phpunit.xml -- it is not the cause" while
     * phpunit.xml WAS the cause. Both halves of the input are real here: the testdox half
     * comes from the binary, the count-only half is master's own pre-S345 shape.
     */
    public function test_a_zero_skip_testdox_run_does_not_hijack_the_diagnosis_of_a_count_only_run(): void
    {
        $testdox = $this->runRealPhpunit([
            self::REAL_TEST_FILE,
            '--testdox',
            '--filter',
            'testListBackupsReturnsAllBackupsSorted',
        ]);

        // Premise, with its own message: this testdox run must skip NOTHING, or it is not
        // the input class this test is about.
        self::assertStringNotContainsString(
            'Skipped:',
            $testdox,
            'the filtered testdox run skipped something after all, so this input is no longer '
            . 'the "testdox present but explains nothing" class — pick another filter',
        );

        $result = $this->runScript($this->fixtureFile(
            'zero-skip-testdox.log',
            $testdox . "\n" . self::COUNT_ONLY,
        ));

        self::assertSame(
            4,
            $result['exit'],
            "testdox that skipped NOTHING explains none of the missing names, so the true cause\n"
            . "is the missing detail list. Exit 5 here would tell the reader to leave phpunit.xml\n"
            . "alone about a run whose only fault IS phpunit.xml. stderr:\n" . $result['stderr'],
        );
        self::assertStringContainsString('displayDetailsOnSkippedTests', $result['stderr']);
        self::assertStringNotContainsString(
            'Do NOT change phpunit.xml',
            $result['stderr'],
            'the exoneration sentence may only appear when testdox accounts for EVERY unnamed '
            . 'skip. This is the round-1 defect in mirror image and it must stay dead.',
        );
    }

    /**
     * Cheaper than a whole testdox run and the same defect: the detector greps the WHOLE
     * input for testdox's glyphs, and the documented recipe is `gh run view --log`, which
     * carries every tool's output. One unrelated line used to flip a correct exit 4 into a
     * false exit 5.
     */
    public function test_one_stray_line_in_testdox_glyph_format_does_not_hijack_the_diagnosis(): void
    {
        $result = $this->runScript($this->fixtureFile(
            'stray-glyph.log',
            " \u{2714} some other tool says ok\n" . self::COUNT_ONLY,
        ));

        self::assertSame(
            4,
            $result['exit'],
            "one line in testdox's glyph format, from anything at all, must not change the\n"
            . "diagnosis of the run that actually lost its detail list. stderr:\n" . $result['stderr'],
        );
        self::assertStringNotContainsString('Do NOT change phpunit.xml', $result['stderr']);
        self::assertStringContainsString(
            'Evidence, not a cause',
            $result['stderr'],
            'the glyph lines should still be REPORTED — suppressing them would trade a false '
            . 'diagnosis for a missing one',
        );
    }

    /**
     * The middle case: testdox explains SOME of the shortfall. Neither "it is testdox, leave
     * the config alone" nor "the config is the only cause" is true, so both are named and the
     * config is not exonerated.
     */
    public function test_testdox_that_explains_only_part_of_the_shortfall_names_both_causes(): void
    {
        $testdox = $this->runRealPhpunit([self::REAL_TEST_FILE, '--testdox']);
        $this->assertTheFixtureStillSkipsExactlyOneTest($testdox);

        $result = $this->runScript($this->fixtureFile(
            'partial-testdox.log',
            $testdox . "\n" . self::COUNT_ONLY,
        ));

        self::assertSame(4, $result['exit'], $result['stderr']);
        self::assertStringContainsString(
            'BOTH causes are in play',
            $result['stderr'],
            'one testdox skip cannot account for five missing names; the message must name the '
            . 'residual as well',
        );
        self::assertStringNotContainsString('Do NOT change phpunit.xml', $result['stderr']);
    }

    /**
     * Round-2 finding 5: `No tests executed!` anywhere in the input used to switch the
     * over-count check off for the whole input, so a genuinely drifting second run rode in
     * free. The allowance is now bounded by what the no-totals runs themselves declared.
     */
    public function test_a_no_totals_run_does_not_excuse_over_counting_elsewhere_in_the_same_log(): void
    {
        $alone = $this->runRealPhpunit([$this->writeSuiteSkipProbe()]);
        self::assertStringContainsString('No tests executed!', $alone, 'the probe stopped skipping its suite');

        // Control: on its own, the no-totals shape is legitimate and must still pass.
        $control = $this->runScript($this->fixtureFile('nototals-alone.log', $alone));
        self::assertSame(0, $control['exit'], $control['stderr']);

        // A second run in the same log declaring 2 while its summary says 1 is real drift,
        // and the first run's missing totals line does not explain it.
        $over = "PHPUnit 10.5.64\n\nThere were 2 skipped tests:\n\n"
            . "1) Phlix\Tests\Unit\Alpha\AlphaTest::testGamma\nreason\n\n"
            . "2) Phlix\Tests\Unit\Beta\BogusTest::testBogus\nreason\n\n"
            . "OK, but some tests were skipped!\nTests: 9, Assertions: 12, Skipped: 1.\n";

        $result = $this->runScript($this->fixtureFile('nototals-plus-drift.log', $alone . "\n" . $over));

        self::assertSame(
            3,
            $result['exit'],
            "the `No tests executed!` allowance must be BOUNDED by what those runs declared (1\n"
            . "here), not switched off for the whole input — otherwise a bogus name rides in on\n"
            . "exit 0. stderr:\n" . $result['stderr'],
        );
        self::assertSame([], $result['lines'], 'no set may be written when the numbers do not add up');
        self::assertStringContainsString('leaving 1 unexplained', $result['stderr']);
    }

    /**
     * Round-3 finding 1, measured verbatim. `declared` is an input-wide SUM, so the entries a
     * `No tests executed!` run declares — which have no `Skipped: N` term of their own — used to
     * cancel a DIFFERENT run's lost names. The shortfall then shrank to what testdox could
     * carry, so exit 5 fired and told the reader "Do NOT change phpunit.xml" about a log
     * containing a run whose list phpunit.xml had genuinely lost. That is round-2's HIGH,
     * verbatim, one layer down.
     *
     * Two of the three halves are the real binary: two suite-skipping probe classes (declared 2,
     * summarised 0) and a real `--testdox` run over a two-skip class (summarised 2, `↩`×2). The
     * third is master's own pre-S345 count-only shape, i.e. `phpunit.xml` really broken for that
     * run.
     *
     * Measured on the pristine script: exit 5, "all 2 skipped test(s) ... are accounted for by
     * testdox output ... Do NOT change phpunit.xml".
     */
    public function test_a_no_totals_runs_entries_cannot_pay_for_another_runs_lost_names(): void
    {
        $suites = $this->runRealPhpunit([
            $this->writeSuiteSkipProbe(),
            $this->writeSuiteSkipProbe('B'),
        ]);

        // Premises, each with its own message, so a broken probe never reads as a broken script.
        self::assertStringContainsString(
            'There were 2 skipped test suites:',
            $suites,
            'the two probe classes no longer skip their whole suites, so this input is not the '
            . 'no-totals shape any more — regenerate the probes, do not touch phpunit.xml',
        );
        self::assertStringNotContainsString('Tests: ', $suites, 'this shape publishes no totals line');

        $testdox = $this->runRealPhpunit([$this->writeTwoTestSkipProbe(), '--testdox']);
        self::assertStringContainsString(
            'Skipped: 2',
            $testdox,
            'the two-skip probe no longer skips two tests, so testdox cannot be the thing that '
            . 'over-carries the shortfall here',
        );
        self::assertSame(
            2,
            preg_match_all('/^ \x{21A9} /mu', $testdox),
            'testdox must print one ↩ glyph per skipped TEST, or this fixture is not measuring '
            . 'the attribution clamp',
        );

        $result = $this->runScript($this->fixtureFile(
            'nototals-testdox-countonly.log',
            $suites . "\n" . $testdox . "\n" . $this->countOnlyRun(2),
        ));

        self::assertSame(
            4,
            $result['exit'],
            "the suite-skip run declared 2 entries with NO count of its own, so they cannot offset\n"
            . "the count-only run's missing list. Exit 5 here is round-2's HIGH resurrected: it\n"
            . "tells the reader to leave phpunit.xml alone about a log in which phpunit.xml IS a\n"
            . "cause. stderr:\n" . $result['stderr'],
        );
        self::assertSame([], $result['lines'], 'no set may be written while names are missing');
        self::assertStringNotContainsString(
            'Do NOT change phpunit.xml',
            $result['stderr'],
            'the exoneration sentence may only appear when testdox accounts for EVERY unnamed '
            . 'skip in the input, and here a count-only run has lost its list',
        );
        self::assertStringContainsString(
            'BOTH causes are in play',
            $result['stderr'],
            'testdox carries part of this shortfall and the missing list carries the rest; both '
            . 'must be named',
        );
    }

    /**
     * Round-3 finding 2, measured verbatim, and the worst outcome the exit contract exists to
     * prevent: the SAME input-wide sum, with no `--testdox` anywhere, made the script hand `comm`
     * a set short by one name and exit 0 — silent loss reported as success. The second run alone
     * is a correct exit 4.
     */
    public function test_a_no_totals_run_does_not_turn_a_count_only_runs_lost_names_into_exit_0(): void
    {
        $alone = $this->runRealPhpunit([$this->writeSuiteSkipProbe()]);
        self::assertStringContainsString(
            'No tests executed!',
            $alone,
            'the probe class no longer skips its whole suite, so this is not the no-totals shape',
        );

        // Control: the same run on its own is legitimate and must still emit its name at exit 0.
        $control = $this->runScript($this->fixtureFile('nototals-only.log', $alone));
        self::assertSame(0, $control['exit'], $control['stderr']);
        self::assertSame(['SUITE:Phlix\Tests\Scratch\S345SuiteSkipProbeTest'], $control['lines']);

        // Control: the count-only run on its own is a correct exit 4.
        $lost = $this->runScript($this->fixtureFile('countonly-1.log', $this->countOnlyRun(1)));
        self::assertSame(4, $lost['exit'], $lost['stderr']);

        $result = $this->runScript($this->fixtureFile(
            'nototals-plus-countonly.log',
            $alone . "\n" . $this->countOnlyRun(1),
        ));

        self::assertSame(
            4,
            $result['exit'],
            "concatenating the two must not cancel them out: exit 0 here writes a set that is\n"
            . "short by the count-only run's name, which is the one outcome this contract exists\n"
            . "to prevent. stderr:\n" . $result['stderr'],
        );
        self::assertSame(
            [],
            $result['lines'],
            'a set that is short by a name must NOT be written — `comm` cannot tell it from a '
            . 'complete one',
        );
        self::assertStringContainsString('displayDetailsOnSkippedTests', $result['stderr']);
    }

    /**
     * The README's headline recipe is a PIPE (`./vendor/bin/phpunit 2>&1 | scripts/...`), and
     * every other test here hands the script a FILE argument instead. That left the stdin path
     * — the only form the documentation tells anyone to use — with no test at all: changing the
     * `${1:--}` default so that stdin is never read left all 29 tests green (measured).
     */
    public function test_the_documented_stdin_pipeline_yields_the_same_set_as_a_file_argument(): void
    {
        $output = $this->runRealPhpunit([self::REAL_TEST_FILE]);
        $this->assertTheFixtureStillSkipsExactlyOneTest($output);

        $log = $this->fixtureFile('pipe.log', $output);

        $viaArgument = $this->runScript($log);
        $viaStdin = $this->runScriptPipedFrom($log);

        self::assertSame(0, $viaStdin['exit'], 'the documented pipe form must work: ' . $viaStdin['stderr']);
        self::assertSame([self::REAL_SKIPPED_NAME], $viaStdin['lines'], $viaStdin['stderr']);
        self::assertSame(
            $viaArgument['lines'],
            $viaStdin['lines'],
            'the pipe and the file argument must produce the SAME set, or the documented recipe '
            . 'and the tested one are two different tools',
        );
    }

    /**
     * `--help` must be answered without reading stdin and without writing to stdout: the
     * documented form has no argument, so a regression that treats `--help` as a FILENAME
     * would either wait on an inherited terminal or emit usage text into the name set, where
     * `comm` cannot tell prose from a skipped test.
     */
    public function test_the_help_flags_are_answered_on_stderr_and_never_pollute_the_set(): void
    {
        foreach (['-h', '--help'] as $flag) {
            $result = $this->runScriptWithArgv([$flag]);

            self::assertSame(0, $result['exit'], $flag . ' must exit 0: ' . $result['stderr']);
            self::assertSame('', $result['stdout'], $flag . ': usage text on stdout would be read as a NAME');
            self::assertStringContainsString('usage: skipped-test-names.sh', $result['stderr'], $flag);
            self::assertStringContainsString(
                '0/2/3/4/5/6',
                $result['stderr'],
                $flag . ': the usage must point at the exit contract, which is the only place the '
                . 'refusal codes are documented',
            );
        }
    }

    /**
     * A FILE argument that cannot be opened has its own exit-2 message, and it must not be
     * reported as "this is not PHPUnit output": that cause sends the reader to re-run PHPUnit
     * when the log was never opened at all. Deleting the guard keeps exit 2 and swaps in the
     * wrong cause, and all 29 earlier tests stayed green under exactly that mutation.
     */
    public function test_a_file_argument_that_cannot_be_read_is_named_rather_than_called_junk(): void
    {
        $missing = $this->tmpDir . '/never-written.log';
        self::assertFileDoesNotExist($missing);

        $result = $this->runScriptWithArgv([$missing]);

        self::assertSame(2, $result['exit'], $result['stderr']);
        self::assertSame('', $result['stdout'], 'nothing may be written to the set from an unreadable input');
        self::assertStringContainsString('cannot read', $result['stderr']);
        self::assertStringContainsString(
            $missing,
            $result['stderr'],
            'the refusal must name the path it could not read',
        );
        self::assertStringNotContainsString(
            'no PHPUnit result summary',
            $result['stderr'],
            'an unopenable path is not "the wrong kind of input" — naming that cause sends the '
            . 'reader to check the command that produced the log instead of the path',
        );
    }

    /**
     * The denominators on stderr are the whole defence against a parser that matched NOTHING
     * reading as a pass, and nothing asserted that they are printed: replacing that `printf`
     * with `true` left all 29 earlier tests green (measured). Asserted on the POPULATED and on
     * the EMPTY set, because the empty one is the case a reader has to be able to audit.
     */
    public function test_the_denominators_are_printed_for_a_populated_and_for_an_empty_set(): void
    {
        $populated = $this->runScript($this->fixtureFile('denominators.log'));

        self::assertSame(0, $populated['exit'], $populated['stderr']);
        self::assertCount(4, $populated['lines'], $populated['stderr']);
        self::assertStringContainsString('4 skipped test(s) in the run summaries', $populated['stderr']);
        self::assertStringContainsString('4 declared by the detail lists', $populated['stderr']);
        self::assertStringContainsString(
            count($populated['lines']) . ' name(s) extracted',
            $populated['stderr'],
            'the number of names emitted must be printed beside the number PHPUnit declared, or '
            . 'a set short by one cannot be spotted at all',
        );

        $empty = $this->runScript($this->fixtureFile(
            'nothing.log',
            "PHPUnit 10.5.64\n\nOK (9 tests, 12 assertions)\n",
        ));

        self::assertSame(0, $empty['exit'], $empty['stderr']);
        self::assertSame([], $empty['lines']);
        self::assertStringContainsString(
            '0 name(s) extracted',
            $empty['stderr'],
            'an empty set must still publish its denominators, or it is indistinguishable from a '
            . 'parser that matched nothing',
        );
        self::assertStringContainsString(
            '1 PHPUnit result summary line(s) seen',
            $empty['stderr'],
            'the positive control must be printed with the empty set, not only used internally',
        );
    }

    /**
     * The falsifiability control for the whole step, which nothing else here supplies: does
     * the attribute actually CAUSE the naming? Every other real-binary test runs WITH it, so
     * all of them would still pass if PHPUnit named skipped tests by default and the attribute
     * were decoration — a correct guard on a config that guards nothing. Measured against a
     * generated config that differs from its own control by that one attribute and nothing
     * else, with the real binary on both sides.
     */
    public function test_the_config_attribute_is_what_makes_the_real_binary_name_a_skip(): void
    {
        $with = $this->runRealPhpunitWithConfig($this->writeProbeConfig(true), [self::REAL_TEST_FILE]);
        $without = $this->runRealPhpunitWithConfig($this->writeProbeConfig(false), [self::REAL_TEST_FILE]);

        // Both runs skip the same single test and both publish the same COUNT, so a count
        // comparison cannot tell them apart. That is the whole reason names were needed.
        self::assertStringContainsString('Skipped: 1', $with, 'premise: the control run skips exactly one test');
        self::assertStringContainsString(
            'Skipped: 1',
            $without,
            'premise: dropping the attribute must change only the NAMES, not the count — if the '
            . 'count moved too, this pair is measuring something else',
        );

        self::assertStringContainsString(
            'skipped test:',
            $with,
            'premise: with the attribute the real binary prints the skipped-details list',
        );
        self::assertStringNotContainsString(
            'skipped test:',
            $without,
            'PHPUnit named the skipped test WITHOUT displayDetailsOnSkippedTests, so the attribute '
            . 'this step installs is decoration and the guard on it guards nothing. Re-derive the '
            . 'mechanism before trusting anything else in this file.',
        );

        $named = $this->runScript($this->fixtureFile('attribute-on.log', $with));
        self::assertSame(0, $named['exit'], $named['stderr']);
        self::assertSame([self::REAL_SKIPPED_NAME], $named['lines'], $named['stderr']);

        $lost = $this->runScript($this->fixtureFile('attribute-off.log', $without));
        self::assertSame(4, $lost['exit'], $lost['stderr']);
        self::assertSame([], $lost['lines'], 'no set may be written when the names were never printed');
        self::assertStringContainsString('displayDetailsOnSkippedTests', $lost['stderr']);
    }

    // ---------------------------------------------------------------------------------
    // helpers
    // ---------------------------------------------------------------------------------

    /**
     * Master's own pre-S345 shape: a run that publishes a skip COUNT and no detail list at all.
     */
    private function countOnlyRun(int $skipped): string
    {
        return "PHPUnit 10.5.64\n\nOK, but there were issues!\n"
            . 'Tests: 9, Assertions: 12, Skipped: ' . $skipped . ".\n";
    }

    /**
     * The premise every real-binary expectation below rests on, asserted with its OWN
     * message: `REAL_TEST_FILE` still skips exactly one test.
     *
     * Round 2 of this step's review found three of those tests failing with "phpunit.xml is
     * not reaching it" when the likelier cause is that somebody made
     * `BackupManagerTest::testCreateBackupGeneratesIdAndPath` stop skipping — which has
     * nothing to do with `phpunit.xml`. `Skipped: N` is printed whatever the config says
     * (`SummaryPrinter.php`), so this check is independent of the thing under test.
     */
    private function assertTheFixtureStillSkipsExactlyOneTest(string $output): void
    {
        self::assertStringContainsString(
            'Skipped: 1',
            $output,
            self::REAL_TEST_FILE . ' no longer skips exactly one test, so every expectation '
            . 'in this test is measuring something else. This is NOT a phpunit.xml problem: '
            . 'the count is printed whatever the config says. Pick another fixture with one '
            . "unconditional markTestSkipped(), or restore this one. Output was:\n" . $output,
        );
    }

    /**
     * The script with its comment lines removed, so an assertion about the script's
     * BEHAVIOUR cannot be satisfied by the script's own prose. Round 2 of this step's
     * review found the byte-order fallback passing on the header's copy-paste one-liner.
     */
    private function scriptCode(): string
    {
        $code = [];

        foreach (explode("\n", (string) file_get_contents(self::SCRIPT)) as $line) {
            if (!str_starts_with(ltrim($line), '#')) {
                $code[] = $line;
            }
        }

        $joined = implode("\n", $code);

        // Anti-vacuity: stripping must leave the script, not empty it.
        self::assertStringContainsString('set -uo pipefail', $joined, 'comment stripping ate the script');
        self::assertStringNotContainsString('THE ONE-LINER', $joined, 'the header comment survived stripping');

        return $joined;
    }

    /**
     * Every workflow file in a directory. GitHub Actions accepts BOTH `.yml` and `.yaml`,
     * and a glob that sees only one of them is a guard with a hole in it.
     *
     * @return list<string>
     */
    private function workflowFiles(string $dir): array
    {
        $files = [
            ...(glob($dir . '/*.yml') ?: []),
            ...(glob($dir . '/*.yaml') ?: []),
        ];

        sort($files);

        return array_values($files);
    }

    /**
     * Every `run:` scalar of every step of every job in one workflow's SOURCE.
     *
     * Parsed, not grepped: a parse drops YAML comments (so the S345 prose that explains
     * why `--testdox` is banned cannot be mistaken for a command) and keeps a `run: |`
     * block whole, which is what makes folding its continuations possible.
     *
     * @return list<string>
     */
    private function runScalars(string $yaml): array
    {
        $parsed = Yaml::parse($yaml);
        self::assertIsArray($parsed, 'workflow does not parse as YAML');

        $out = [];

        foreach ((is_array($parsed['jobs'] ?? null) ? $parsed['jobs'] : []) as $job) {
            if (!is_array($job) || !is_array($job['steps'] ?? null)) {
                continue;
            }

            foreach ($job['steps'] as $step) {
                if (is_array($step) && is_string($step['run'] ?? null)) {
                    $out[] = $step['run'];
                }
            }
        }

        return $out;
    }

    /**
     * A shell body split into LOGICAL command lines: `\`-continuations folded into one
     * line, and any unquoted `#` comment removed.
     *
     * Both halves are load-bearing. Without the folding, `--testdox` on its own
     * continuation line is invisible to a per-line check. Stripping at the FIRST `#`
     * regardless of quoting (the previous version) hides the rest of a command that
     * legitimately contains one, e.g. `--filter '#[Group]'`.
     *
     * @return list<string>
     */
    private function logicalCommandLines(string $shell): array
    {
        // Fold `\` + newline (plus the continuation's leading indent) into a single space.
        $folded = preg_replace('/\\\\\n\s*/', ' ', $shell) ?? $shell;

        $out = [];

        foreach (explode("\n", $folded) as $line) {
            $quote = '';
            $code = '';

            foreach (str_split($line === '' ? ' ' : $line) as $index => $char) {
                if ($quote !== '') {
                    $quote = $char === $quote ? '' : $quote;
                } elseif ($char === '"' || $char === "'") {
                    $quote = $char;
                } elseif ($char === '#' && ($index === 0 || preg_match('/\s/', $line[$index - 1]) === 1)) {
                    break;
                }

                $code .= $char;
            }

            $out[] = trim($code);
        }

        return $out;
    }

    /**
     * Every place in one workflow's source where PHPUnit is invoked with `--testdox`.
     *
     * `--testdox` is matched as a whitespace-delimited TOKEN, so `--testdox-html` and
     * `--testdox-text` — logging targets that do not put PHPUnit into testdox output mode
     * (Cli/Builder.php:851-862) — are not false positives.
     *
     * @return list<string>
     */
    private function testdoxOffenders(string $yaml, string $label): array
    {
        $out = [];

        foreach ($this->runScalars($yaml) as $run) {
            foreach ($this->logicalCommandLines($run) as $line) {
                if (!str_contains($line, 'phpunit')) {
                    continue;
                }

                foreach (preg_split('/\s+/', $line) ?: [] as $token) {
                    if (trim($token, "'\"") === '--testdox') {
                        $out[] = $label . ': ' . $line;

                        continue 2;
                    }
                }
            }
        }

        return $out;
    }

    private function fixtureFile(string $name, ?string $contents = null): string
    {
        $path = $this->tmpDir . '/' . $name;
        file_put_contents($path, ($contents ?? self::FIXTURE) . "\n");

        return $path;
    }

    /**
     * Writes a throwaway test class whose `setUpBeforeClass()` skips, which is how PHPUnit
     * emits a testSuiteSkipped event. Returns its path. `$tag` yields a SECOND, distinct
     * class so that one run can skip two suites (round-3 finding 1's input needs `There were
     * 2 skipped test suites:` in a single run).
     */
    private function writeSuiteSkipProbe(string $tag = ''): string
    {
        $class = 'S345SuiteSkipProbe' . $tag . 'Test';
        $path = $this->tmpDir . '/' . $class . '.php';

        $template = <<<'PROBE'
            <?php

            declare(strict_types=1);

            namespace Phlix\Tests\Scratch;

            use PHPUnit\Framework\TestCase;

            final class __CLASS_NAME__ extends TestCase
            {
                public static function setUpBeforeClass(): void
                {
                    self::markTestSkipped('S345 probe: the whole suite is skipped');
                }

                public function test_never_runs(): void
                {
                    self::assertTrue(true);
                }
            }
            PROBE;

        file_put_contents($path, str_replace('__CLASS_NAME__', $class, $template));

        return $path;
    }

    /**
     * Writes a throwaway test class with TWO unconditional test-level skips, so a `--testdox`
     * run over it prints `Skipped: 2` and two `↩` glyphs. Returns its path.
     */
    private function writeTwoTestSkipProbe(): string
    {
        $path = $this->tmpDir . '/S345TwoSkipProbeTest.php';

        file_put_contents($path, <<<'PROBE'
            <?php

            declare(strict_types=1);

            namespace Phlix\Tests\Scratch;

            use PHPUnit\Framework\TestCase;

            final class S345TwoSkipProbeTest extends TestCase
            {
                public function test_first(): void
                {
                    self::markTestSkipped('S345 probe: skip 1 of 2');
                }

                public function test_second(): void
                {
                    self::markTestSkipped('S345 probe: skip 2 of 2');
                }
            }
            PROBE);

        return $path;
    }

    /**
     * @param list<string> $args
     */
    private function runRealPhpunit(array $args): string
    {
        $root = realpath(self::REPO);
        self::assertIsString($root);
        self::assertFileExists($root . '/vendor/bin/phpunit');

        $command = 'cd ' . escapeshellarg($root) . ' && '
            . escapeshellarg(PHP_BINARY) . ' ' . escapeshellarg($root . '/vendor/bin/phpunit')
            . ' -c ' . escapeshellarg($root . '/phpunit.xml')
            . ' --no-coverage --colors=never';

        foreach ($args as $argument) {
            $command .= ' ' . escapeshellarg($argument);
        }

        $out = $this->tmpDir . '/phpunit-run.txt';
        exec($command . ' > ' . escapeshellarg($out) . ' 2>&1');

        $output = (string) file_get_contents($out);
        @unlink($out);

        self::assertStringContainsString(
            'PHPUnit 10.5',
            $output,
            "the real phpunit binary produced no recognisable output, so nothing below is measuring "
            . "anything:\n" . $output,
        );

        return $output;
    }

    /**
     * Finds a locale installed on this box whose collation orders C_ORDER_PAIR the other
     * way round, DERIVED by running `sort` rather than hard-coded.
     */
    private function localeWhoseCollationDiffersFromC(): ?string
    {
        $file = $this->tmpDir . '/collate.txt';
        file_put_contents($file, self::C_ORDER_PAIR[1] . "\n" . self::C_ORDER_PAIR[0] . "\n");

        $locales = [];
        exec('locale -a 2>/dev/null', $locales);

        foreach ($locales as $locale) {
            if (!str_contains(strtolower($locale), 'utf')) {
                continue;
            }

            $sorted = [];
            exec('LC_ALL=' . escapeshellarg($locale) . ' sort ' . escapeshellarg($file) . ' 2>/dev/null', $sorted);

            if (array_values($sorted) !== self::C_ORDER_PAIR) {
                @unlink($file);

                return $locale;
            }
        }

        @unlink($file);

        return null;
    }

    /**
     * @param array<string, string> $env
     *
     * @return array{exit: int, stdout: string, lines: list<string>, stderr: string}
     */
    private function runScript(string $input, array $env = []): array
    {
        $stdoutFile = $this->tmpDir . '/stdout.txt';
        $stderrFile = $this->tmpDir . '/stderr.txt';

        $prefix = '';
        foreach ($env as $name => $value) {
            $prefix .= $name . '=' . escapeshellarg($value) . ' ';
        }

        $exit = 0;
        exec(
            $prefix . escapeshellarg(self::SCRIPT) . ' ' . escapeshellarg($input)
            . ' > ' . escapeshellarg($stdoutFile) . ' 2> ' . escapeshellarg($stderrFile),
            $ignored,
            $exit,
        );

        $stdout = (string) file_get_contents($stdoutFile);

        return [
            'exit' => $exit,
            'stdout' => $stdout,
            // Deliberately NOT filtered: a blank line is a set member for `comm`, so it must
            // be able to fail an assertion rather than be dropped on the way in.
            'lines' => $stdout === '' ? [] : explode("\n", rtrim($stdout, "\n")),
            'stderr' => (string) file_get_contents($stderrFile),
        ];
    }

    /**
     * A config that differs from the repo's only in whether it asks for skipped-test NAMES, so
     * a difference measured with it is that attribute and nothing else. Written into the
     * fixture directory with ABSOLUTE paths and `cacheResult="false"`, so no cwd is involved
     * and no artefact is left in the repo or in the fixture directory.
     */
    private function writeProbeConfig(bool $displaySkipped): string
    {
        $root = realpath(self::REPO);
        self::assertIsString($root);

        $attribute = $displaySkipped ? ' displayDetailsOnSkippedTests="true"' : '';
        $path = $this->tmpDir . '/probe-config-' . ($displaySkipped ? 'on' : 'off') . '.xml';

        file_put_contents($path, <<<XML
            <?xml version="1.0" encoding="UTF-8"?>
            <phpunit bootstrap="{$root}/tests/bootstrap.php" cacheResult="false" colors="false"{$attribute}>
              <testsuites>
                <testsuite name="S345Probe">
                  <directory suffix="Test.php">{$root}/tests/Unit/Admin</directory>
                </testsuite>
              </testsuites>
            </phpunit>
            XML);

        return $path;
    }

    /**
     * `runRealPhpunit()` with a config chosen by the caller. Kept separate rather than folded
     * into it, so the existing expectations keep running against the REPO's phpunit.xml.
     *
     * @param list<string> $args
     */
    private function runRealPhpunitWithConfig(string $config, array $args): string
    {
        $root = realpath(self::REPO);
        self::assertIsString($root);
        self::assertFileExists($root . '/vendor/bin/phpunit');

        $command = 'cd ' . escapeshellarg($root) . ' && '
            . escapeshellarg(PHP_BINARY) . ' ' . escapeshellarg($root . '/vendor/bin/phpunit')
            . ' -c ' . escapeshellarg($config)
            . ' --no-coverage --colors=never';

        foreach ($args as $argument) {
            $command .= ' ' . escapeshellarg($argument);
        }

        $out = $this->tmpDir . '/phpunit-config-run.txt';
        exec($command . ' > ' . escapeshellarg($out) . ' 2>&1');

        $output = (string) file_get_contents($out);
        @unlink($out);

        self::assertStringContainsString(
            'PHPUnit 10.5',
            $output,
            "the real phpunit binary produced no recognisable output with " . $config
            . ", so nothing measured from it means anything:\n" . $output,
        );

        return $output;
    }

    /**
     * The script with an explicit argv and stdin closed off, for the argument handling
     * `runScript()` cannot reach (`--help`, and a path that will not open). stdin is
     * redirected from `/dev/null` on purpose: a regression that falls through to reading it
     * then FAILS here instead of hanging the suite on an inherited terminal.
     *
     * @param list<string> $argv
     *
     * @return array{exit: int, stdout: string, lines: list<string>, stderr: string}
     */
    private function runScriptWithArgv(array $argv): array
    {
        $command = escapeshellarg(self::SCRIPT);

        foreach ($argv as $argument) {
            $command .= ' ' . escapeshellarg($argument);
        }

        return $this->captureScript($command . ' < /dev/null');
    }

    /**
     * The DOCUMENTED form: `<a run's output> | scripts/skipped-test-names.sh`, no argument.
     *
     * @return array{exit: int, stdout: string, lines: list<string>, stderr: string}
     */
    private function runScriptPipedFrom(string $file): array
    {
        return $this->captureScript('cat ' . escapeshellarg($file) . ' | ' . escapeshellarg(self::SCRIPT));
    }

    /**
     * @return array{exit: int, stdout: string, lines: list<string>, stderr: string}
     */
    private function captureScript(string $command): array
    {
        $stdoutFile = $this->tmpDir . '/argv-stdout.txt';
        $stderrFile = $this->tmpDir . '/argv-stderr.txt';

        $exit = 0;
        exec(
            $command . ' > ' . escapeshellarg($stdoutFile) . ' 2> ' . escapeshellarg($stderrFile),
            $ignored,
            $exit,
        );

        $stdout = (string) file_get_contents($stdoutFile);

        return [
            'exit' => $exit,
            'stdout' => $stdout,
            // Not filtered, for the same reason as `runScript()`: a blank line is a set member.
            'lines' => $stdout === '' ? [] : explode("\n", rtrim($stdout, "\n")),
            'stderr' => (string) file_get_contents($stderrFile),
        ];
    }
}
