<?php

declare(strict_types=1);

namespace Phlix\Tests\Unit\Contracts;

use Phlix\Session\SyncPlay\Messages;
use Phlix\Session\SyncPlay\SyncPlayManager;
use Phlix\Server\Http\Controllers\PluginAdminController;
use Phlix\Server\Http\Controllers\PluginCatalogController;
use Phlix\Server\Http\Response;
use Phlix\Tests\Support\Contracts\ErrorCodeScan;
use PHPUnit\Framework\TestCase;
use ReflectionMethod;
use ReflectionNamedType;

/**
 * W2 (error-code doctrine) — the server consumes the @phlix/contracts error-code
 * registry, and every code the server places on a wire `code`/`error_code` field
 * is a registered member.
 *
 * ## What this file enforces
 *
 *  1. **Vendored-fixture honesty.** `tests/Fixtures/Contracts/error-codes.json` is
 *     a byte-copy of `dist/error-codes.json` from the @phlix/contracts tag
 *     {@see ErrorCodesContractTest::CONTRACTS_TAG}. The fixture's own `$comment`
 *     must still carry the generator marker (a hand-written impostor fails), the
 *     sidecar pin file must name the same tag this test hardcodes (re-vendor is a
 *     two-file lockstep edit), and the registry must clear the anti-vacuity floor.
 *
 *  2. **The emit law.** A positional scan ({@see ErrorCodeScan}) of every PHP
 *     file under `src/` finds each expression the source places on a code-carrying
 *     wire field, and every literal found there must be a member of the vendored
 *     registry. The scan is POSITIONAL, not shape-based: a dotted string appearing
 *     anywhere (config key, webhook event name, codec profile) is NOT an emitted
 *     code. A whole-tree shape census was measured before this law was written and
 *     surfaced 174 non-registry dotted literals that are not error codes at all —
 *     positional scanning is why this law does not need a hand-written denylist.
 *
 *  3. **Channels.** A scanned site is `ws` when its value travels on a SyncPlay
 *     WebSocket frame (`Messages::error()` arg 0, `sendError()` arg 1, an
 *     `'error_code' =>` array key) and `rest` otherwise (`'code' =>` array key,
 *     `Response::error()` arg 1, `jsonError()` arg 1). The split exists because
 *     {@see ErrorCodesOpenApiEnumContractTest} pins only the REST channel against
 *     `openapi.yaml` `Error.code` — the WS channel carries the legacy SCREAMING
 *     and dotted-twin vocabularies and is specified by the SyncPlay wire SPEC,
 *     not by this OpenAPI document.
 *
 *  4. **Emitter allow-list pin.** The call-argument patterns are driven by an
 *     explicit emitter table ({@see CODE_EMITTERS}); every entry's signature is
 *     re-checked against reflection on every run, so renaming the `$code`
 *     parameter, deleting a helper, or pointing the table at a non-string
 *     parameter reddens this test instead of silently shrinking coverage. The
 *     definition-side twin ({@see test_every_string_code_parameter_is_a_declared_emitter()})
 *     reddens when a NEW helper declares an int-first `string $code` signature
 *     returning Response/self and nobody registers it — the hole is closed from
 *     both sides.
 *
 *  5. **Whitelist honesty.** Non-literal code-channel expressions (variables,
 *     properties, calls) cannot be registry-checked statically. Each such site is
 *     listed in {@see NON_LITERAL_WHITELIST} with file, normalized expression,
 *     channel and reason — and the list is LIVE-checked in both directions: every
 *     scanned non-literal site must appear in it, and every entry must match a
 *     site still present in the tree, so the list cannot fossilize.
 *     {@see LITERAL_EXCEPTIONS} works the same way for logged sentinels that
 *     merely look like code emissions.
 *
 * Fix the CONTRACT first (phlix-contracts src/errors.ts, retag, re-vendor), then
 * the emitter. Never invent a code in server source.
 *
 * @package Phlix
 */
final class ErrorCodesContractTest extends TestCase
{
    /**
     * The contracts tag the fixture was vendored from. Bumping this WITHOUT
     * re-vendoring reddens {@see test_the_fixture_is_vendored_from_the_pinned_contract_tag()};
     * re-vendoring a different tag WITHOUT bumping this reddens it too.
     */
    public const CONTRACTS_TAG = 'v0.5.1';

    public const GENERATOR_MARKER = 'GENERATED by scripts/emit-error-codes.mjs';

    /**
     * Anti-vacuity floor: the v0.5.1 registry carries 202 codes; 147 is the floor
     * recorded when this lane opened. A truncated re-vendor cannot pass.
     */
    public const MIN_REGISTRY_CODES = 147;

    /** Floor on distinct code-channel literals the scan must find (drift alarm). */
    public const MIN_SCANNED_DISTINCT_CODES = 40;

    /**
     * Code-emitting functions: class FQCN, method, 0-based code argument index,
     * channel, and the parameter name the code travels in. Reflection-pinned every
     * run ({@see test_emitter_table_matches_live_signatures()}).
     */
    public const CODE_EMITTERS = [
        ['class' => Messages::class, 'method' => 'error', 'arg' => 0, 'channel' => 'ws', 'param' => 'code'],
        ['class' => SyncPlayManager::class, 'method' => 'sendError', 'arg' => 1, 'channel' => 'ws', 'param' => 'code'],
        ['class' => Response::class, 'method' => 'error', 'arg' => 1, 'channel' => 'rest', 'param' => 'code'],
        ['class' => PluginAdminController::class, 'method' => 'jsonError', 'arg' => 1, 'channel' => 'rest', 'param' => 'code'],
        ['class' => PluginCatalogController::class, 'method' => 'jsonError', 'arg' => 1, 'channel' => 'rest', 'param' => 'code'],
    ];

    /**
     * Non-literal code-channel sites whose values cannot be registry-checked
     * statically. Live-checked in both directions by
     * {@see test_every_non_literal_code_channel_site_is_whitelisted_and_live()}.
     *
     * @var list<array{file: string, expr: string, channel: string, reason: string}>
     */
    public const NON_LITERAL_WHITELIST = [
        // UPnP/SOAP numeric fault codes: a different envelope and vocabulary, never
        // the Phlix Error.code channel.
        ['file' => 'Dlna/AvTransport.php', 'expr' => '$code', 'channel' => 'rest', 'reason' => 'SOAP/UPnP fault code int, not an Error.code'],
        ['file' => 'Dlna/CdsControlHandler.php', 'expr' => '$code', 'channel' => 'rest', 'reason' => 'SOAP/UPnP fault code int, not an Error.code'],
        ['file' => 'Dlna/ContentDirectory.php', 'expr' => '$code', 'channel' => 'rest', 'reason' => 'SOAP/UPnP fault code int, not an Error.code'],
        // Hub-link internals: logged or relayed HUB codes, never server-emitted.
        ['file' => 'Hub/HubClient.php', 'expr' => '$errorCode', 'channel' => 'ws', 'reason' => 'hub-log context; hub vocabulary, not server-emitted'],
        ['file' => 'Hub/HubClient.php', 'expr' => '$result->errorCode', 'channel' => 'ws', 'reason' => 'hub-log context; hub vocabulary, not server-emitted'],
        ['file' => 'Hub/RelayConsumer.php', 'expr' => '$code', 'channel' => 'rest', 'reason' => 'Workerman socket-error int into logger context'],
        ['file' => 'Hub/RelayConsumer.php', 'expr' => '$payload[\'code\'] ?? null', 'channel' => 'rest', 'reason' => 'inbound hub ERROR frame logged verbatim'],
        // Provider/storage internals: an upstream HTTP status and OAuth
        // authorization codes (request params, not errors) riding `code` keys.
        ['file' => 'Media/Storage/ArtworkStorage.php', 'expr' => '$httpCode', 'channel' => 'rest', 'reason' => 'upstream HTTP status in an own response shape, not an Error.code'],
        ['file' => 'Server/Integrations/Trakt/TraktApi.php', 'expr' => '$code', 'channel' => 'rest', 'reason' => 'OAuth authorization code POST param, not an error'],
        ['file' => 'Plugins/OAuth2/AbstractOAuth2Provider.php', 'expr' => '$code', 'channel' => 'rest', 'reason' => 'OAuth authorization code POST param, not an error'],
        ['file' => 'Plugins/Oidc/OidcProvider.php', 'expr' => '$code', 'channel' => 'rest', 'reason' => 'OIDC authorization code POST param, not an error'],
        ['file' => 'Plugins/Github/Controller/GithubCallbackController.php', 'expr' => '$code', 'channel' => 'rest', 'reason' => 'OAuth authorization code inbound param'],
        ['file' => 'Plugins/Oidc/Controller/OidcCallbackController.php', 'expr' => '$code', 'channel' => 'rest', 'reason' => 'OIDC authorization code inbound param'],
        // The Quick-Connect pairing code and per-field plugin validation codes are
        // code-named fields from their own vocabularies, not Error.code emissions.
        ['file' => 'Server/Http/Controllers/Auth/QuickConnectController.php', 'expr' => '$pair->code', 'channel' => 'rest', 'reason' => 'Quick-Connect pairing code value, not an error code'],
        ['file' => 'Server/Http/Controllers/PluginAdminController.php', 'expr' => '$err->code', 'channel' => 'rest', 'reason' => 'per-field validation code from the shared plugin-config vocabulary'],
        // Emitter-builder interiors: the values are checked at every call site.
        ['file' => 'Server/Http/Controllers/PluginAdminController.php', 'expr' => '$code', 'channel' => 'rest', 'reason' => 'jsonError() builder body; literals guarded at call sites'],
        ['file' => 'Server/Http/Controllers/PluginCatalogController.php', 'expr' => '$code', 'channel' => 'rest', 'reason' => 'jsonError() builder body; literals guarded at call sites'],
        ['file' => 'Server/Http/Response.php', 'expr' => '$code', 'channel' => 'rest', 'reason' => 'Response::error() builder body; literals guarded at call sites'],
        ['file' => 'Session/SyncPlay/Messages.php', 'expr' => '$code', 'channel' => 'ws', 'reason' => 'Messages::error() factory body; literals guarded at call sites'],
        ['file' => 'Session/SyncPlay/SyncPlayManager.php', 'expr' => 'error($code)', 'channel' => 'ws', 'reason' => 'sendError() body forwarding into Messages::error; literals guarded at call sites'],
        // Hub binary ERROR-frame DECODE (inbound protocol parsing, not an emit).
        ['file' => 'Server/WebSocket/SyncPlay/Protocol.php', 'expr' => '$errorCode', 'channel' => 'ws', 'reason' => 'hub binary ERROR-frame decode, not server-emitted'],
        // Auth dynamic exception code — see DYNAMIC_CODE_CHANNELS.
        ['file' => 'Server/Http/Controllers/AuthController.php', 'expr' => '$e->errorCode', 'channel' => 'rest', 'reason' => 'exception-carried code; bridged via DYNAMIC_CODE_CHANNELS'],
        // Logger contexts on Workerman socket errors (int errno, own vocabulary).
        ['file' => 'Server/WebSocket/WebSocketServer.php', 'expr' => '$code', 'channel' => 'rest', 'reason' => 'Workerman socket-error int into logger context'],
        ['file' => 'Server/WebSocket/Workers/SyncPlayWorker.php', 'expr' => '$code', 'channel' => 'rest', 'reason' => 'Workerman socket-error int into logger context'],
    ];

    /**
     * Literals at code-channel positions that are not wire emits (logged
     * sentinels). Live-anchored like NON_LITERAL_WHITELIST.
     *
     * @var list<array{file: string, expr: string, channel: string, reason: string}>
     */
    public const LITERAL_EXCEPTIONS = [
        ['file' => 'Hub/HubClient.php', 'expr' => '$response->getErrorCode() ?? \'UNKNOWN\'', 'channel' => 'ws', 'reason' => 'hub-log sentinel, not a wire emit'],
    ];

    /**
     * Codes that reach the REST `code` field through a dynamic expression the
     * scanner cannot resolve (an exception property fed by named constructors).
     * Declared here, registry-checked here; the enum law inherits them.
     *
     * @var list<string>
     */
    public const DYNAMIC_CODE_CHANNELS = [
        'auth.account_pending',          // AccountInactiveException::ERROR_PENDING  via forStatus()
        'auth.account_disabled',         // AccountInactiveException::ERROR_DISABLED via forStatus()
        'auth.password_change_required', // PasswordChangeRequiredException::ERROR_CODE
    ];

    /**
     * file => snippets whose presence keeps DYNAMIC_CODE_CHANNELS honest.
     *
     * @var array<string, list<string>>
     */
    public const DYNAMIC_CODE_CHANNEL_ANCHORS = [
        'Auth/AccountInactiveException.php' => ['self::ERROR_PENDING', 'self::ERROR_DISABLED'],
        'Auth/PasswordChangeRequiredException.php' => ['self::ERROR_CODE'],
        'Server/Http/Controllers/AuthController.php' => ['$e->errorCode'],
    ];

    // ── fixture + pin laws ───────────────────────────────────────────────

    private static function fixture_path(): string
    {
        return dirname(__DIR__, 2) . '/Fixtures/Contracts/error-codes.json';
    }

    private static function pin_path(): string
    {
        return dirname(__DIR__, 2) . '/Fixtures/Contracts/error-codes.pin.txt';
    }

    public static function src_root(): string
    {
        return dirname(__DIR__, 3) . '/src';
    }

    /** @return list<string> */
    public static function registry_codes(): array
    {
        $decoded = self::read_json(self::fixture_path());
        if (!is_array($decoded) || !isset($decoded['codes']) || !is_array($decoded['codes'])) {
            self::fail('the vendored registry must decode to {codes: [...]}.');
        }
        /** @var list<string> $codes */
        $codes = $decoded['codes'];
        return $codes;
    }

    /** @return array<mixed>|list<mixed>|null */
    private static function read_json(string $path): mixed
    {
        return json_decode(self::read_text($path), true, 512, JSON_THROW_ON_ERROR);
    }

    private static function read_text(string $path): string
    {
        self::assertFileExists($path);
        $raw = file_get_contents($path);
        self::assertIsString($raw);
        return $raw;
    }

    public function test_the_fixture_is_vendored_from_the_pinned_contract_tag(): void
    {
        $pin = trim(self::read_text(self::pin_path()));

        $this->assertSame(
            self::CONTRACTS_TAG,
            $pin,
            "the sidecar pin says '{$pin}' but this test hardcodes '" . self::CONTRACTS_TAG . "'. "
            . 'Re-vendor tests/Fixtures/Contracts/error-codes.json from the @phlix/contracts tag this test names, and keep both files in lockstep.',
        );
    }

    public function test_the_fixture_is_generator_output_not_a_hand_written_impostor(): void
    {
        $raw = self::read_text(self::fixture_path());

        $this->assertStringContainsString(
            self::GENERATOR_MARKER,
            $raw,
            'error-codes.json must stay the byte-copy of dist/error-codes.json produced by the contracts generator.',
        );
    }

    public function test_the_registry_clears_the_anti_vacuity_floor(): void
    {
        $codes = self::registry_codes();

        $this->assertGreaterThanOrEqual(
            self::MIN_REGISTRY_CODES,
            count($codes),
            'a truncated re-vendor cannot pass: the floor records the size of the registry at adoption time.',
        );
        $this->assertSame(array_values(array_unique($codes)), $codes, 'registry codes must be unique and in declared order.');
    }

    // ── the emit law ──────────────────────────────────────────────────────

    public function test_every_code_channel_literal_is_registered(): void
    {
        $registry = array_flip(self::registry_codes());
        $sites = ErrorCodeScan::run(self::src_root());

        $distinct = [];
        $violations = [];
        foreach ($sites as $site) {
            if ($site['kind'] !== 'literal' && $site['kind'] !== 'const') {
                continue;
            }
            if (isset(self::exception_keys()[self::site_key($site)])) {
                continue;
            }
            $distinct[$site['value']] = true;
            if (!isset($registry[$site['value']])) {
                $violations[] = "{$site['file']}:{$site['line']} [{$site['channel']}] '{$site['value']}' (expr: {$site['snippet']})";
            }
        }

        $this->assertGreaterThanOrEqual(
            self::MIN_SCANNED_DISTINCT_CODES,
            count($distinct),
            'the scanner found almost no code-channel literals — the positional patterns broke; fix the scan, do not celebrate a green law.',
        );

        $this->assertSame(
            [],
            $violations,
            "codes placed on a wire code field but absent from the vendored registry (fix the CONTRACT first, then re-vendor; never invent):\n"
            . implode("\n", $violations),
        );
    }

    public function test_emitted_codes_cover_both_channels(): void
    {
        $channels = [];
        foreach (ErrorCodeScan::run(self::src_root()) as $site) {
            $channels[$site['channel']] = ($channels[$site['channel']] ?? 0) + 1;
        }

        $this->assertArrayHasKey('rest', $channels, 'the REST channel scanner stopped matching anything — positional patterns broke.');
        $this->assertArrayHasKey('ws', $channels, 'the WS channel scanner stopped matching anything — positional patterns broke.');
    }

    public function test_every_non_literal_code_channel_site_is_whitelisted_and_live(): void
    {
        $scan = [];
        foreach (ErrorCodeScan::run(self::src_root()) as $site) {
            if ($site['kind'] === 'nonliteral' || $site['kind'] === 'const-unresolved') {
                $scan[self::site_key($site)] = $site;
            }
        }

        $whitelist = [];
        foreach (self::NON_LITERAL_WHITELIST as $entry) {
            $key = "{$entry['file']}|{$entry['channel']}|{$entry['expr']}";
            $this->assertArrayNotHasKey($key, $whitelist, "duplicate whitelist entry: {$key}");
            $this->assertNotSame('', $entry['reason'], "every whitelist entry needs a reason: {$key}");
            $whitelist[$key] = $entry;
        }

        $unwhitelisted = array_values(array_diff(array_keys($scan), array_keys($whitelist)));
        $stale = array_values(array_diff(array_keys($whitelist), array_keys($scan)));

        $this->assertSame(
            [],
            $unwhitelisted,
            "non-literal code-channel sites without a whitelisted reason (classify them, or route their values through the registry-checked Response::error()/jsonError() pattern):\n"
            . implode("\n", $unwhitelisted),
        );
        $this->assertSame(
            [],
            $stale,
            "whitelist entries whose site no longer exists in src/ — the tree moved, prune the list:\n"
            . implode("\n", $stale),
        );
    }

    public function test_every_literal_exception_is_registered_anchored_and_live(): void
    {
        $scan = [];
        foreach (ErrorCodeScan::run(self::src_root()) as $site) {
            if ($site['kind'] === 'literal') {
                $scan[self::site_key($site)] = $site;
            }
        }

        $seen = [];
        foreach (self::LITERAL_EXCEPTIONS as $entry) {
            $key = "{$entry['file']}|{$entry['channel']}|{$entry['expr']}";
            $this->assertArrayNotHasKey($key, $seen, "duplicate literal exception: {$key}");
            $this->assertNotSame('', $entry['reason'], "every literal exception needs a reason: {$key}");
            $this->assertArrayHasKey(
                $key,
                $scan,
                "literal exception '{$key}' matches no scanned site — prune it (the tree moved or the pattern broke).",
            );
            $seen[$key] = true;
        }
    }

    // ── emitter + dynamic-code laws ───────────────────────────────────────

    public function test_emitter_table_matches_live_signatures(): void
    {
        foreach (self::CODE_EMITTERS as $emitter) {
            $method = new ReflectionMethod("{$emitter['class']}::{$emitter['method']}");
            $params = $method->getParameters();
            $this->assertArrayHasKey(
                $emitter['arg'],
                $params,
                "{$emitter['class']}::{$emitter['method']}() has no argument {$emitter['arg']} — the emitter table lies.",
            );
            $param = $params[$emitter['arg']];
            $this->assertSame(
                $emitter['param'],
                $param->getName(),
                "the emitter table expects parameter \${$emitter['param']} at position {$emitter['arg']} of {$emitter['method']}().",
            );
            $type = $param->getType();
            $this->assertInstanceOf(ReflectionNamedType::class, $type);
            $this->assertSame('string', $type->getName());
        }
    }

    public function test_every_string_code_parameter_is_a_declared_emitter(): void
    {
        $declared = [];
        foreach (self::CODE_EMITTERS as $emitter) {
            $declared["{$emitter['class']}::{$emitter['method']}"] = true;
        }

        $undeclared = [];
        foreach (ErrorCodeScan::emitterDefinitions(self::src_root()) as $fqn) {
            if (!isset($declared[$fqn])) {
                $undeclared[] = $fqn;
            }
        }

        $this->assertSame(
            [],
            $undeclared,
            "methods declaring an int-first `string \$code` signature returning Response/self are code emitters — register them in CODE_EMITTERS (or rename the parameter):\n"
            . implode("\n", $undeclared),
        );
    }

    public function test_dynamic_code_channel_codes_are_registered(): void
    {
        $registry = array_flip(self::registry_codes());
        foreach (self::DYNAMIC_CODE_CHANNELS as $code) {
            $this->assertArrayHasKey($code, $registry, "a code reachable via a dynamic code channel is not in the registry: {$code}");
        }

        foreach (self::DYNAMIC_CODE_CHANNEL_ANCHORS as $relFile => $anchors) {
            $raw = self::read_text(self::src_root() . '/' . $relFile);
            foreach ($anchors as $anchor) {
                $this->assertStringContainsString(
                    $anchor,
                    $raw,
                    "the dynamic-code-channel anchor '{$anchor}' vanished from {$relFile} — re-audit the channel.",
                );
            }
        }
    }

    /**
     * The REST-emittable set: every code the server can place on `Error.code`.
     * Consumed by {@see ErrorCodesOpenApiEnumContractTest}.
     *
     * @return list<string> registry-declared order
     */
    public static function rest_emittable_codes(): array
    {
        $found = [];
        foreach (ErrorCodeScan::run(self::src_root()) as $site) {
            if (($site['kind'] === 'literal' || $site['kind'] === 'const') && $site['channel'] === 'rest') {
                if (isset(self::exception_keys()[self::site_key($site)])) {
                    continue;
                }
                $found[$site['value']] = true;
            }
        }
        foreach (self::DYNAMIC_CODE_CHANNELS as $code) {
            $found[$code] = true;
        }

        $registry = self::registry_codes();
        $ordered = [];
        foreach ($registry as $code) {
            if (isset($found[$code])) {
                $ordered[] = $code;
            }
        }
        // Anything the scan found that the registry does not declare cannot be
        // ordered — the emit law already reddens on it first; surface it loudly
        // here too rather than silently dropping it from the enum.
        foreach (array_keys($found) as $code) {
            if (!in_array((string) $code, $registry, true)) {
                $ordered[] = (string) $code;
            }
        }
        return $ordered;
    }

    /** @return array<string, true> */
    private static function exception_keys(): array
    {
        $out = [];
        foreach (self::LITERAL_EXCEPTIONS as $entry) {
            $out["{$entry['file']}|{$entry['channel']}|{$entry['expr']}"] = true;
        }
        return $out;
    }

    /**
     * @param array{file: string, line: int, channel: string, kind: string, value?: string, snippet: string} $site
     */
    private static function site_key(array $site): string
    {
        return "{$site['file']}|{$site['channel']}|{$site['snippet']}";
    }
}
