apiVersion: v1
kind: Service
metadata:
  name: {{ include "phlix.fullname" . }}
  labels:
    {{- include "phlix.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.websocket.port }}
      targetPort: websocket
      protocol: TCP
      name: websocket
  selector:
    {{- include "phlix.selectorLabels" . | nindent 4 }}
